// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : JBochenek
Date           : Thu Apr 12 10:53:10 2012
Host           : Linux lnxthry05.hep.fsu.edu 2.6.18-238.5.1.el5 #1 SMP Fri Apr 1 18:41:58 EDT 2011 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/room2/jbochenek/HiggsCombination/TMVAfiles/TMVA-v4.1.2/test
Training events: 10000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "1200" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 19
mu1_pt                        mu1_pt                        mu1_pt                        mu1_pt                                                          'F'    [20.0387992859,278.061004639]
mu1_eta                       mu1_eta                       mu1_eta                       mu1_eta                                                         'F'    [-2.39956998825,2.39913010597]
mu1_phi                       mu1_phi                       mu1_phi                       mu1_phi                                                         'F'    [-3.14155006409,3.14138007164]
mu2_pt                        mu2_pt                        mu2_pt                        mu2_pt                                                          'F'    [8.8874502182,150.102005005]
mu2_eta                       mu2_eta                       mu2_eta                       mu2_eta                                                         'F'    [-2.39977002144,2.39869999886]
mu2_phi                       mu2_phi                       mu2_phi                       mu2_phi                                                         'F'    [-3.14139008522,3.14006996155]
mu3_pt                        mu3_pt                        mu3_pt                        mu3_pt                                                          'F'    [5.29546022415,90.4963989258]
mu3_eta                       mu3_eta                       mu3_eta                       mu3_eta                                                         'F'    [-2.39901995659,2.398250103]
mu3_phi                       mu3_phi                       mu3_phi                       mu3_phi                                                         'F'    [-3.14122009277,3.14109992981]
mu4_pt                        mu4_pt                        mu4_pt                        mu4_pt                                                          'F'    [5.00129985809,69.7885971069]
mu4_eta                       mu4_eta                       mu4_eta                       mu4_eta                                                         'F'    [-2.3996899128,2.39824008942]
mu4_phi                       mu4_phi                       mu4_phi                       mu4_phi                                                         'F'    [-3.14139008522,3.14139008522]
worst_iso_X                   worst_iso_X                   worst_iso_X                   worst_iso_X                                                     'F'    [-0.0444267988205,14.0198001862]
second_worst_iso_X            second_worst_iso_X            second_worst_iso_X            second_worst_iso_X                                              'F'    [-0.0540362000465,1.85469996929]
worst_vertex                  worst_vertex                  worst_vertex                  worst_vertex                                                    'F'    [0.275514006615,96.7269973755]
second_worst_vertex           second_worst_vertex           second_worst_vertex           second_worst_vertex                                             'F'    [0.135326996446,44.9584999084]
mZ                            mZ                            mZ                            mZ                                                              'F'    [8.75,140.74899292]
mZstar                        mZstar                        mZstar                        mZstar                                                          'F'    [12.0004997253,111.925003052]
mbestH                        mbestH                        mbestH                        mbestH                                                          'F'    [110.018997192,164.99899292]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 19 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "mu1_pt", "mu1_eta", "mu1_phi", "mu2_pt", "mu2_eta", "mu2_phi", "mu3_pt", "mu3_eta", "mu3_phi", "mu4_pt", "mu4_eta", "mu4_phi", "worst_iso_X", "second_worst_iso_X", "worst_vertex", "second_worst_vertex", "mZ", "mZstar", "mbestH" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 0.99999988079071;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;
      fVmin[13] = -1;
      fVmax[13] = 1;
      fVmin[14] = -1;
      fVmax[14] = 1;
      fVmin[15] = -1;
      fVmax[15] = 1;
      fVmin[16] = -1;
      fVmax[16] = 1;
      fVmin[17] = -1;
      fVmax[17] = 1;
      fVmin[18] = -1;
      fVmax[18] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][19];
   double fMax_1[3][19];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[19];
   double fVmax[19];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[19];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[25][20];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][25];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 20; fWeights[0] = new double[20]; 
   fLayerSize[1] = 25; fWeights[1] = new double[25]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.824359516229676;
   fWeightMatrix0to1[1][0] = 1.94354356589057;
   fWeightMatrix0to1[2][0] = 2.82835254387461;
   fWeightMatrix0to1[3][0] = 1.66052726604267;
   fWeightMatrix0to1[4][0] = -1.21220632114421;
   fWeightMatrix0to1[5][0] = -2.21887002053351;
   fWeightMatrix0to1[6][0] = -1.13609748829533;
   fWeightMatrix0to1[7][0] = 2.87988097068536;
   fWeightMatrix0to1[8][0] = 1.50973499974829;
   fWeightMatrix0to1[9][0] = -0.361125046070135;
   fWeightMatrix0to1[10][0] = -1.31818741795638;
   fWeightMatrix0to1[11][0] = -1.15505546943777;
   fWeightMatrix0to1[12][0] = -1.68225350784156;
   fWeightMatrix0to1[13][0] = -1.46037295195677;
   fWeightMatrix0to1[14][0] = -0.395154980692641;
   fWeightMatrix0to1[15][0] = -0.607702685026689;
   fWeightMatrix0to1[16][0] = 0.572075450265078;
   fWeightMatrix0to1[17][0] = 1.57427192418358;
   fWeightMatrix0to1[18][0] = -1.03347342930617;
   fWeightMatrix0to1[19][0] = 0.819885143882476;
   fWeightMatrix0to1[20][0] = -1.39295013289533;
   fWeightMatrix0to1[21][0] = 0.591823571828495;
   fWeightMatrix0to1[22][0] = 1.88830370248583;
   fWeightMatrix0to1[23][0] = 0.444270211158855;
   fWeightMatrix0to1[0][1] = -2.89132356350861;
   fWeightMatrix0to1[1][1] = -0.203099410978537;
   fWeightMatrix0to1[2][1] = -0.823949852944574;
   fWeightMatrix0to1[3][1] = -1.09340830088226;
   fWeightMatrix0to1[4][1] = -0.519989691779015;
   fWeightMatrix0to1[5][1] = 0.692738277999898;
   fWeightMatrix0to1[6][1] = 0.196260302141745;
   fWeightMatrix0to1[7][1] = 0.964290889444593;
   fWeightMatrix0to1[8][1] = -1.70926454941875;
   fWeightMatrix0to1[9][1] = -0.661473082870662;
   fWeightMatrix0to1[10][1] = 0.363875436447324;
   fWeightMatrix0to1[11][1] = -0.279496123416788;
   fWeightMatrix0to1[12][1] = -1.20431447342399;
   fWeightMatrix0to1[13][1] = 1.13761364102277;
   fWeightMatrix0to1[14][1] = -1.59116157689661;
   fWeightMatrix0to1[15][1] = -0.224966808559842;
   fWeightMatrix0to1[16][1] = 0.225555513955332;
   fWeightMatrix0to1[17][1] = 0.260592563846568;
   fWeightMatrix0to1[18][1] = 0.404867791094352;
   fWeightMatrix0to1[19][1] = 0.918966426415265;
   fWeightMatrix0to1[20][1] = -0.859639487722628;
   fWeightMatrix0to1[21][1] = -0.45516910910693;
   fWeightMatrix0to1[22][1] = -2.23915081892765;
   fWeightMatrix0to1[23][1] = 0.529151496847655;
   fWeightMatrix0to1[0][2] = 0.239954984263589;
   fWeightMatrix0to1[1][2] = 1.45429384871073;
   fWeightMatrix0to1[2][2] = -0.183061693310015;
   fWeightMatrix0to1[3][2] = 1.18536268585498;
   fWeightMatrix0to1[4][2] = 0.23033802013291;
   fWeightMatrix0to1[5][2] = 1.09138171699578;
   fWeightMatrix0to1[6][2] = -0.502650010124947;
   fWeightMatrix0to1[7][2] = 0.0238410191862645;
   fWeightMatrix0to1[8][2] = -0.233329708807781;
   fWeightMatrix0to1[9][2] = -1.16513891816219;
   fWeightMatrix0to1[10][2] = 1.22604755994578;
   fWeightMatrix0to1[11][2] = 0.615573521192504;
   fWeightMatrix0to1[12][2] = -1.51641413252719;
   fWeightMatrix0to1[13][2] = -0.111048999328929;
   fWeightMatrix0to1[14][2] = 0.217181539911528;
   fWeightMatrix0to1[15][2] = 0.343373451761508;
   fWeightMatrix0to1[16][2] = 0.059192007026818;
   fWeightMatrix0to1[17][2] = 0.211315452170378;
   fWeightMatrix0to1[18][2] = 0.00786444292262403;
   fWeightMatrix0to1[19][2] = 0.00541925546810597;
   fWeightMatrix0to1[20][2] = -0.066699939649806;
   fWeightMatrix0to1[21][2] = -1.09837744667207;
   fWeightMatrix0to1[22][2] = -0.697282782529919;
   fWeightMatrix0to1[23][2] = -0.232977911601854;
   fWeightMatrix0to1[0][3] = 0.223214003188091;
   fWeightMatrix0to1[1][3] = 1.10123753543164;
   fWeightMatrix0to1[2][3] = 0.627835650898945;
   fWeightMatrix0to1[3][3] = -0.338700689523173;
   fWeightMatrix0to1[4][3] = -1.06882716144361;
   fWeightMatrix0to1[5][3] = -2.87423942901399;
   fWeightMatrix0to1[6][3] = 0.0670943146637718;
   fWeightMatrix0to1[7][3] = 0.567141551837694;
   fWeightMatrix0to1[8][3] = 1.50046134311581;
   fWeightMatrix0to1[9][3] = 1.60108073210946;
   fWeightMatrix0to1[10][3] = 1.32683868604246;
   fWeightMatrix0to1[11][3] = -1.47467243071087;
   fWeightMatrix0to1[12][3] = -1.17969415952812;
   fWeightMatrix0to1[13][3] = -1.16064591420374;
   fWeightMatrix0to1[14][3] = 0.845300956253768;
   fWeightMatrix0to1[15][3] = -0.298406714889148;
   fWeightMatrix0to1[16][3] = -0.209286754831425;
   fWeightMatrix0to1[17][3] = -1.4657463037333;
   fWeightMatrix0to1[18][3] = 0.746775526596717;
   fWeightMatrix0to1[19][3] = 2.2674849763831;
   fWeightMatrix0to1[20][3] = 0.611192681884093;
   fWeightMatrix0to1[21][3] = -1.29019375565525;
   fWeightMatrix0to1[22][3] = -0.496632364259071;
   fWeightMatrix0to1[23][3] = 2.57053707433663;
   fWeightMatrix0to1[0][4] = -1.07241615336884;
   fWeightMatrix0to1[1][4] = -1.49547373305734;
   fWeightMatrix0to1[2][4] = -1.18114535646021;
   fWeightMatrix0to1[3][4] = 0.177371613325727;
   fWeightMatrix0to1[4][4] = -2.82826308639482;
   fWeightMatrix0to1[5][4] = -2.4581265429465;
   fWeightMatrix0to1[6][4] = -0.387287517605148;
   fWeightMatrix0to1[7][4] = 0.162019202005214;
   fWeightMatrix0to1[8][4] = -0.524749590478501;
   fWeightMatrix0to1[9][4] = 1.45797698958741;
   fWeightMatrix0to1[10][4] = -1.09426667487047;
   fWeightMatrix0to1[11][4] = -0.72738133751527;
   fWeightMatrix0to1[12][4] = 0.0807258856363022;
   fWeightMatrix0to1[13][4] = 0.215225874275377;
   fWeightMatrix0to1[14][4] = -2.09623656576263;
   fWeightMatrix0to1[15][4] = -0.535901972051312;
   fWeightMatrix0to1[16][4] = 0.0441353716844387;
   fWeightMatrix0to1[17][4] = -0.35890236284064;
   fWeightMatrix0to1[18][4] = -0.746788857434963;
   fWeightMatrix0to1[19][4] = 2.02583624742721;
   fWeightMatrix0to1[20][4] = 0.541559374883622;
   fWeightMatrix0to1[21][4] = -0.989785960084688;
   fWeightMatrix0to1[22][4] = 3.30195210221454;
   fWeightMatrix0to1[23][4] = -1.09397449387449;
   fWeightMatrix0to1[0][5] = -1.10758932272879;
   fWeightMatrix0to1[1][5] = 0.11819809583434;
   fWeightMatrix0to1[2][5] = -0.36730028258594;
   fWeightMatrix0to1[3][5] = 1.74331441350689;
   fWeightMatrix0to1[4][5] = -0.712166492267501;
   fWeightMatrix0to1[5][5] = 0.727471763536592;
   fWeightMatrix0to1[6][5] = -0.244498879925504;
   fWeightMatrix0to1[7][5] = -0.368165579602281;
   fWeightMatrix0to1[8][5] = -0.188720859836779;
   fWeightMatrix0to1[9][5] = -0.457169442399705;
   fWeightMatrix0to1[10][5] = 0.542977634519087;
   fWeightMatrix0to1[11][5] = -1.70557328107621;
   fWeightMatrix0to1[12][5] = 0.612588931254058;
   fWeightMatrix0to1[13][5] = -1.68820429810837;
   fWeightMatrix0to1[14][5] = 0.35159532532842;
   fWeightMatrix0to1[15][5] = 0.183014272789884;
   fWeightMatrix0to1[16][5] = -0.0461523838063645;
   fWeightMatrix0to1[17][5] = -5.45479609532005;
   fWeightMatrix0to1[18][5] = -0.372384054670162;
   fWeightMatrix0to1[19][5] = 0.0373707694390773;
   fWeightMatrix0to1[20][5] = 0.741913255102386;
   fWeightMatrix0to1[21][5] = -0.140139604659132;
   fWeightMatrix0to1[22][5] = -2.44038539099231;
   fWeightMatrix0to1[23][5] = 0.986905094064744;
   fWeightMatrix0to1[0][6] = -2.43220675911249;
   fWeightMatrix0to1[1][6] = 1.54349444844727;
   fWeightMatrix0to1[2][6] = 1.96391884969579;
   fWeightMatrix0to1[3][6] = -0.60068591109632;
   fWeightMatrix0to1[4][6] = 1.88691182042191;
   fWeightMatrix0to1[5][6] = 0.018686780746593;
   fWeightMatrix0to1[6][6] = -2.98181807904409;
   fWeightMatrix0to1[7][6] = 1.95122605281713;
   fWeightMatrix0to1[8][6] = 3.25788266383406;
   fWeightMatrix0to1[9][6] = -0.338760280082161;
   fWeightMatrix0to1[10][6] = -0.221653539388377;
   fWeightMatrix0to1[11][6] = -0.309848685964915;
   fWeightMatrix0to1[12][6] = 0.738876174965336;
   fWeightMatrix0to1[13][6] = -0.425339941095955;
   fWeightMatrix0to1[14][6] = 0.514344366617153;
   fWeightMatrix0to1[15][6] = 0.0438880594803822;
   fWeightMatrix0to1[16][6] = -0.294612812360784;
   fWeightMatrix0to1[17][6] = 0.117530209221434;
   fWeightMatrix0to1[18][6] = -0.990755482338209;
   fWeightMatrix0to1[19][6] = 1.59338421571922;
   fWeightMatrix0to1[20][6] = 0.259691109105905;
   fWeightMatrix0to1[21][6] = 0.689201599853198;
   fWeightMatrix0to1[22][6] = -2.59742914130166;
   fWeightMatrix0to1[23][6] = 0.354762610432779;
   fWeightMatrix0to1[0][7] = -1.50693151493804;
   fWeightMatrix0to1[1][7] = -0.571848417341726;
   fWeightMatrix0to1[2][7] = 4.77010766058152;
   fWeightMatrix0to1[3][7] = 0.969639164172888;
   fWeightMatrix0to1[4][7] = -2.36659200038001;
   fWeightMatrix0to1[5][7] = 1.67678431160307;
   fWeightMatrix0to1[6][7] = 0.367384566176875;
   fWeightMatrix0to1[7][7] = -2.93845878132653;
   fWeightMatrix0to1[8][7] = -1.90243596811659;
   fWeightMatrix0to1[9][7] = -0.767751730146595;
   fWeightMatrix0to1[10][7] = 0.125231700712105;
   fWeightMatrix0to1[11][7] = -1.42141231282239;
   fWeightMatrix0to1[12][7] = -1.26949297030636;
   fWeightMatrix0to1[13][7] = 0.808091619260336;
   fWeightMatrix0to1[14][7] = 3.03434139830857;
   fWeightMatrix0to1[15][7] = 0.633306021470576;
   fWeightMatrix0to1[16][7] = -0.239309487376216;
   fWeightMatrix0to1[17][7] = 0.254239798748711;
   fWeightMatrix0to1[18][7] = -0.0619237185952652;
   fWeightMatrix0to1[19][7] = 1.04893735305754;
   fWeightMatrix0to1[20][7] = -0.358107033931284;
   fWeightMatrix0to1[21][7] = -0.919499408189882;
   fWeightMatrix0to1[22][7] = -1.10698018260672;
   fWeightMatrix0to1[23][7] = -1.27480298575759;
   fWeightMatrix0to1[0][8] = -0.67359375592302;
   fWeightMatrix0to1[1][8] = 1.09530478530853;
   fWeightMatrix0to1[2][8] = -0.0552191152786269;
   fWeightMatrix0to1[3][8] = -0.429083157644784;
   fWeightMatrix0to1[4][8] = -0.64144828830126;
   fWeightMatrix0to1[5][8] = -0.242625298163292;
   fWeightMatrix0to1[6][8] = -0.273424262404727;
   fWeightMatrix0to1[7][8] = -0.187158385464048;
   fWeightMatrix0to1[8][8] = 0.0991882989983339;
   fWeightMatrix0to1[9][8] = -0.223016177819599;
   fWeightMatrix0to1[10][8] = -0.153811308343145;
   fWeightMatrix0to1[11][8] = -1.38120665510638;
   fWeightMatrix0to1[12][8] = 1.10566209303455;
   fWeightMatrix0to1[13][8] = 0.0177680553686785;
   fWeightMatrix0to1[14][8] = 0.736891724852485;
   fWeightMatrix0to1[15][8] = 0.646570245197732;
   fWeightMatrix0to1[16][8] = -0.136133423213599;
   fWeightMatrix0to1[17][8] = 1.71139479892543;
   fWeightMatrix0to1[18][8] = -0.121541693918953;
   fWeightMatrix0to1[19][8] = -0.0913054919226903;
   fWeightMatrix0to1[20][8] = -1.81425447638865;
   fWeightMatrix0to1[21][8] = 0.393623469609858;
   fWeightMatrix0to1[22][8] = 0.445657394242924;
   fWeightMatrix0to1[23][8] = 1.59040175557373;
   fWeightMatrix0to1[0][9] = 1.7154564470861;
   fWeightMatrix0to1[1][9] = 0.217956148994293;
   fWeightMatrix0to1[2][9] = 2.25014126430016;
   fWeightMatrix0to1[3][9] = -1.87647676840459;
   fWeightMatrix0to1[4][9] = -1.88073344073563;
   fWeightMatrix0to1[5][9] = 0.380060155762384;
   fWeightMatrix0to1[6][9] = -3.39015324008499;
   fWeightMatrix0to1[7][9] = 1.32669792714209;
   fWeightMatrix0to1[8][9] = 2.22401347918584;
   fWeightMatrix0to1[9][9] = -1.50211506273471;
   fWeightMatrix0to1[10][9] = 1.23631635779675;
   fWeightMatrix0to1[11][9] = -0.803505863919531;
   fWeightMatrix0to1[12][9] = -2.18254020962705;
   fWeightMatrix0to1[13][9] = -2.30469197770518;
   fWeightMatrix0to1[14][9] = 0.132602837835305;
   fWeightMatrix0to1[15][9] = -2.37480007075562;
   fWeightMatrix0to1[16][9] = -1.29290592305408;
   fWeightMatrix0to1[17][9] = -1.94869340548743;
   fWeightMatrix0to1[18][9] = 1.5007792000419;
   fWeightMatrix0to1[19][9] = -0.821276848479933;
   fWeightMatrix0to1[20][9] = -0.262937671554073;
   fWeightMatrix0to1[21][9] = 0.532619697729986;
   fWeightMatrix0to1[22][9] = -2.45738518151044;
   fWeightMatrix0to1[23][9] = -1.80819406159399;
   fWeightMatrix0to1[0][10] = -0.0184938610742692;
   fWeightMatrix0to1[1][10] = -0.370473605589964;
   fWeightMatrix0to1[2][10] = -2.40986343183093;
   fWeightMatrix0to1[3][10] = -1.35329812894845;
   fWeightMatrix0to1[4][10] = -2.52079575926171;
   fWeightMatrix0to1[5][10] = 0.19089409174927;
   fWeightMatrix0to1[6][10] = -0.313663328212064;
   fWeightMatrix0to1[7][10] = 1.43161834030983;
   fWeightMatrix0to1[8][10] = 4.51957478741264;
   fWeightMatrix0to1[9][10] = -0.411268751111413;
   fWeightMatrix0to1[10][10] = 0.223941607443556;
   fWeightMatrix0to1[11][10] = -0.839231135973954;
   fWeightMatrix0to1[12][10] = 0.274871293204519;
   fWeightMatrix0to1[13][10] = 1.02236136334431;
   fWeightMatrix0to1[14][10] = 1.29797978500251;
   fWeightMatrix0to1[15][10] = 0.0754754151382521;
   fWeightMatrix0to1[16][10] = 0.113332256023045;
   fWeightMatrix0to1[17][10] = -0.371941808162932;
   fWeightMatrix0to1[18][10] = 0.0957994274620968;
   fWeightMatrix0to1[19][10] = -3.79455540381555;
   fWeightMatrix0to1[20][10] = 0.191754051960716;
   fWeightMatrix0to1[21][10] = 0.236497084808233;
   fWeightMatrix0to1[22][10] = 3.07728743325678;
   fWeightMatrix0to1[23][10] = 0.734990785907254;
   fWeightMatrix0to1[0][11] = -0.887101028674866;
   fWeightMatrix0to1[1][11] = -0.517363982735336;
   fWeightMatrix0to1[2][11] = -0.0548347863828556;
   fWeightMatrix0to1[3][11] = 0.929840643300044;
   fWeightMatrix0to1[4][11] = 0.763117528070681;
   fWeightMatrix0to1[5][11] = -2.26019409129822;
   fWeightMatrix0to1[6][11] = -0.178772672945655;
   fWeightMatrix0to1[7][11] = 0.483690841386724;
   fWeightMatrix0to1[8][11] = -0.239737056124245;
   fWeightMatrix0to1[9][11] = -0.00297897765174475;
   fWeightMatrix0to1[10][11] = -0.531147297265674;
   fWeightMatrix0to1[11][11] = -0.181728829989194;
   fWeightMatrix0to1[12][11] = 1.03709736047701;
   fWeightMatrix0to1[13][11] = 0.813758597035814;
   fWeightMatrix0to1[14][11] = 0.213296825818169;
   fWeightMatrix0to1[15][11] = -0.085627323075448;
   fWeightMatrix0to1[16][11] = -0.151105548444064;
   fWeightMatrix0to1[17][11] = -0.678701411842262;
   fWeightMatrix0to1[18][11] = -0.397142539920681;
   fWeightMatrix0to1[19][11] = -0.0998873386759177;
   fWeightMatrix0to1[20][11] = -1.17394365946119;
   fWeightMatrix0to1[21][11] = -0.695169219060947;
   fWeightMatrix0to1[22][11] = -1.87339846479397;
   fWeightMatrix0to1[23][11] = 0.458638087776068;
   fWeightMatrix0to1[0][12] = -1.86930748163552;
   fWeightMatrix0to1[1][12] = 1.71942890466168;
   fWeightMatrix0to1[2][12] = -2.06964861179156;
   fWeightMatrix0to1[3][12] = 0.846646627504012;
   fWeightMatrix0to1[4][12] = -0.103190296263682;
   fWeightMatrix0to1[5][12] = 0.892414849541084;
   fWeightMatrix0to1[6][12] = 0.831178533109093;
   fWeightMatrix0to1[7][12] = -2.51491009155507;
   fWeightMatrix0to1[8][12] = -0.223286563913419;
   fWeightMatrix0to1[9][12] = 1.1580414672062;
   fWeightMatrix0to1[10][12] = -1.32009912536633;
   fWeightMatrix0to1[11][12] = -2.19992725896467;
   fWeightMatrix0to1[12][12] = -2.17020098520435;
   fWeightMatrix0to1[13][12] = -2.08640225774842;
   fWeightMatrix0to1[14][12] = 1.73492163117011;
   fWeightMatrix0to1[15][12] = 1.76607354090828;
   fWeightMatrix0to1[16][12] = -3.23970489954927;
   fWeightMatrix0to1[17][12] = -0.36695021071846;
   fWeightMatrix0to1[18][12] = -3.89364388670793;
   fWeightMatrix0to1[19][12] = -2.51795934232664;
   fWeightMatrix0to1[20][12] = -2.20263728513632;
   fWeightMatrix0to1[21][12] = -1.83319199487316;
   fWeightMatrix0to1[22][12] = 0.530127777327897;
   fWeightMatrix0to1[23][12] = -2.08945804874143;
   fWeightMatrix0to1[0][13] = -0.9403920170894;
   fWeightMatrix0to1[1][13] = 1.81319659358866;
   fWeightMatrix0to1[2][13] = 1.47432108971453;
   fWeightMatrix0to1[3][13] = -0.86707603602988;
   fWeightMatrix0to1[4][13] = 1.98188954058905;
   fWeightMatrix0to1[5][13] = -1.42993746061131;
   fWeightMatrix0to1[6][13] = 1.25975319260025;
   fWeightMatrix0to1[7][13] = 1.94902799417696;
   fWeightMatrix0to1[8][13] = 0.18152717966305;
   fWeightMatrix0to1[9][13] = -1.03184422440153;
   fWeightMatrix0to1[10][13] = 0.755309131528974;
   fWeightMatrix0to1[11][13] = -1.72824961244669;
   fWeightMatrix0to1[12][13] = 0.102213412174241;
   fWeightMatrix0to1[13][13] = 0.987713509991759;
   fWeightMatrix0to1[14][13] = 1.21982407916836;
   fWeightMatrix0to1[15][13] = 3.41641229372835;
   fWeightMatrix0to1[16][13] = -5.55998731651406;
   fWeightMatrix0to1[17][13] = 1.68467447630957;
   fWeightMatrix0to1[18][13] = -2.95317888601183;
   fWeightMatrix0to1[19][13] = 1.25028456018286;
   fWeightMatrix0to1[20][13] = -2.36550572245354;
   fWeightMatrix0to1[21][13] = -1.80106334733108;
   fWeightMatrix0to1[22][13] = -1.07672046469935;
   fWeightMatrix0to1[23][13] = 0.230168704815103;
   fWeightMatrix0to1[0][14] = 0.157531735120802;
   fWeightMatrix0to1[1][14] = 1.10783851045183;
   fWeightMatrix0to1[2][14] = -1.42290046605083;
   fWeightMatrix0to1[3][14] = -0.578585028347295;
   fWeightMatrix0to1[4][14] = 1.085446196568;
   fWeightMatrix0to1[5][14] = 0.718414703388387;
   fWeightMatrix0to1[6][14] = 7.86083924997667;
   fWeightMatrix0to1[7][14] = -4.87904639210649;
   fWeightMatrix0to1[8][14] = -2.63449445703273;
   fWeightMatrix0to1[9][14] = -0.50107279089119;
   fWeightMatrix0to1[10][14] = 0.389526706772932;
   fWeightMatrix0to1[11][14] = -0.500618949768155;
   fWeightMatrix0to1[12][14] = -0.240345141061227;
   fWeightMatrix0to1[13][14] = -1.8045688093031;
   fWeightMatrix0to1[14][14] = 0.792012729661276;
   fWeightMatrix0to1[15][14] = 5.14244050118915;
   fWeightMatrix0to1[16][14] = -0.700270967047395;
   fWeightMatrix0to1[17][14] = 0.11740139891575;
   fWeightMatrix0to1[18][14] = -7.18306389808148;
   fWeightMatrix0to1[19][14] = -2.55373802940862;
   fWeightMatrix0to1[20][14] = -2.35954640037445;
   fWeightMatrix0to1[21][14] = -0.569161896924447;
   fWeightMatrix0to1[22][14] = -1.52637255933162;
   fWeightMatrix0to1[23][14] = -1.76206155517217;
   fWeightMatrix0to1[0][15] = 0.595631908672715;
   fWeightMatrix0to1[1][15] = -1.65447039410177;
   fWeightMatrix0to1[2][15] = -1.25090104992792;
   fWeightMatrix0to1[3][15] = -2.0015488081634;
   fWeightMatrix0to1[4][15] = 2.24438975341362;
   fWeightMatrix0to1[5][15] = -1.26811772653296;
   fWeightMatrix0to1[6][15] = 0.344608360569612;
   fWeightMatrix0to1[7][15] = -2.17174247919112;
   fWeightMatrix0to1[8][15] = -2.25250233699208;
   fWeightMatrix0to1[9][15] = -0.875000484760766;
   fWeightMatrix0to1[10][15] = 2.09674927391983;
   fWeightMatrix0to1[11][15] = -1.92965409088084;
   fWeightMatrix0to1[12][15] = -1.72321535592782;
   fWeightMatrix0to1[13][15] = 0.421026196794353;
   fWeightMatrix0to1[14][15] = 0.383543508014376;
   fWeightMatrix0to1[15][15] = 0.964164580759288;
   fWeightMatrix0to1[16][15] = -0.371963492015958;
   fWeightMatrix0to1[17][15] = 1.26073042983052;
   fWeightMatrix0to1[18][15] = 2.30466694298021;
   fWeightMatrix0to1[19][15] = -0.0276022024544742;
   fWeightMatrix0to1[20][15] = -1.8501390932849;
   fWeightMatrix0to1[21][15] = -1.44045328341978;
   fWeightMatrix0to1[22][15] = -2.5051396127118;
   fWeightMatrix0to1[23][15] = 1.5847338468932;
   fWeightMatrix0to1[0][16] = 1.08445351371248;
   fWeightMatrix0to1[1][16] = 0.0696987120252371;
   fWeightMatrix0to1[2][16] = 1.40259162767849;
   fWeightMatrix0to1[3][16] = 1.00748256594712;
   fWeightMatrix0to1[4][16] = 1.9224561876687;
   fWeightMatrix0to1[5][16] = 0.260580994336416;
   fWeightMatrix0to1[6][16] = 0.220787162303447;
   fWeightMatrix0to1[7][16] = 0.0147067512971718;
   fWeightMatrix0to1[8][16] = 0.445667497767397;
   fWeightMatrix0to1[9][16] = 0.471302381024307;
   fWeightMatrix0to1[10][16] = -1.14851521614395;
   fWeightMatrix0to1[11][16] = 0.557489447992105;
   fWeightMatrix0to1[12][16] = 0.591549899217862;
   fWeightMatrix0to1[13][16] = 0.854753359966381;
   fWeightMatrix0to1[14][16] = 1.63323724061028;
   fWeightMatrix0to1[15][16] = 1.53889343258269;
   fWeightMatrix0to1[16][16] = -0.115761071823525;
   fWeightMatrix0to1[17][16] = -0.0104216444671049;
   fWeightMatrix0to1[18][16] = 1.34584578647442;
   fWeightMatrix0to1[19][16] = 0.554839666370707;
   fWeightMatrix0to1[20][16] = 0.962057813973298;
   fWeightMatrix0to1[21][16] = -2.85239727627315;
   fWeightMatrix0to1[22][16] = 1.38123435416567;
   fWeightMatrix0to1[23][16] = 3.07600114830002;
   fWeightMatrix0to1[0][17] = 0.894711859285129;
   fWeightMatrix0to1[1][17] = -0.791295425040856;
   fWeightMatrix0to1[2][17] = -0.616267386999307;
   fWeightMatrix0to1[3][17] = -1.55509299810331;
   fWeightMatrix0to1[4][17] = 0.882798795077646;
   fWeightMatrix0to1[5][17] = -1.71962853205681;
   fWeightMatrix0to1[6][17] = -1.70087017080534;
   fWeightMatrix0to1[7][17] = 1.45053590753738;
   fWeightMatrix0to1[8][17] = 0.436149584479228;
   fWeightMatrix0to1[9][17] = 1.50914715811271;
   fWeightMatrix0to1[10][17] = 1.33861953540609;
   fWeightMatrix0to1[11][17] = -0.917736215305335;
   fWeightMatrix0to1[12][17] = -0.637654524140511;
   fWeightMatrix0to1[13][17] = 0.0585583964724932;
   fWeightMatrix0to1[14][17] = 1.24668385677868;
   fWeightMatrix0to1[15][17] = -2.00739631002952;
   fWeightMatrix0to1[16][17] = -0.81939825784331;
   fWeightMatrix0to1[17][17] = -1.68101798711311;
   fWeightMatrix0to1[18][17] = 0.464709612466223;
   fWeightMatrix0to1[19][17] = 1.45354542145613;
   fWeightMatrix0to1[20][17] = -1.84657391220654;
   fWeightMatrix0to1[21][17] = 2.21871796298599;
   fWeightMatrix0to1[22][17] = -2.91980588721608;
   fWeightMatrix0to1[23][17] = -3.33009153214828;
   fWeightMatrix0to1[0][18] = -2.55862997971885;
   fWeightMatrix0to1[1][18] = -0.158899049199632;
   fWeightMatrix0to1[2][18] = -0.472798164089585;
   fWeightMatrix0to1[3][18] = 1.48047718905751;
   fWeightMatrix0to1[4][18] = 2.60167534225121;
   fWeightMatrix0to1[5][18] = 0.326377210937163;
   fWeightMatrix0to1[6][18] = -0.00817908632437101;
   fWeightMatrix0to1[7][18] = -1.20595959986723;
   fWeightMatrix0to1[8][18] = -1.61448323545605;
   fWeightMatrix0to1[9][18] = -2.3668097388039;
   fWeightMatrix0to1[10][18] = -0.708605991338713;
   fWeightMatrix0to1[11][18] = 0.0120111018826459;
   fWeightMatrix0to1[12][18] = -0.970756159963851;
   fWeightMatrix0to1[13][18] = 0.821365948818089;
   fWeightMatrix0to1[14][18] = 0.717427113074035;
   fWeightMatrix0to1[15][18] = 4.56948512963578;
   fWeightMatrix0to1[16][18] = -5.12778275258125;
   fWeightMatrix0to1[17][18] = -1.84761132333688;
   fWeightMatrix0to1[18][18] = -0.656075783775615;
   fWeightMatrix0to1[19][18] = -1.16638121065726;
   fWeightMatrix0to1[20][18] = 0.266885590283965;
   fWeightMatrix0to1[21][18] = 1.86834732889501;
   fWeightMatrix0to1[22][18] = 1.7981590881332;
   fWeightMatrix0to1[23][18] = -1.46066397328084;
   fWeightMatrix0to1[0][19] = 0.633526427556613;
   fWeightMatrix0to1[1][19] = -1.95241167310229;
   fWeightMatrix0to1[2][19] = -0.0472096542861804;
   fWeightMatrix0to1[3][19] = 2.07905696241271;
   fWeightMatrix0to1[4][19] = -0.388314063820673;
   fWeightMatrix0to1[5][19] = -0.255701753351268;
   fWeightMatrix0to1[6][19] = 2.36313042179566;
   fWeightMatrix0to1[7][19] = -2.18903594838469;
   fWeightMatrix0to1[8][19] = 0.148174657279512;
   fWeightMatrix0to1[9][19] = -0.340848309822432;
   fWeightMatrix0to1[10][19] = -1.32513915270941;
   fWeightMatrix0to1[11][19] = -0.58370525393999;
   fWeightMatrix0to1[12][19] = 0.494199171231569;
   fWeightMatrix0to1[13][19] = 3.27499764644575;
   fWeightMatrix0to1[14][19] = 0.592241772750438;
   fWeightMatrix0to1[15][19] = 4.18848466824113;
   fWeightMatrix0to1[16][19] = -4.33695150830139;
   fWeightMatrix0to1[17][19] = 2.67439954939459;
   fWeightMatrix0to1[18][19] = -8.56394203739047;
   fWeightMatrix0to1[19][19] = -2.00577507317122;
   fWeightMatrix0to1[20][19] = 1.17596304884116;
   fWeightMatrix0to1[21][19] = -1.89661442008626;
   fWeightMatrix0to1[22][19] = 1.15363227181587;
   fWeightMatrix0to1[23][19] = 0.248373969286015;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.403410317647443;
   fWeightMatrix1to2[0][1] = -0.139408928289334;
   fWeightMatrix1to2[0][2] = 1.07079424334169;
   fWeightMatrix1to2[0][3] = 0.405586866961349;
   fWeightMatrix1to2[0][4] = -0.436856890433037;
   fWeightMatrix1to2[0][5] = -2.45216500172984;
   fWeightMatrix1to2[0][6] = -0.980114051214024;
   fWeightMatrix1to2[0][7] = 0.802930570592005;
   fWeightMatrix1to2[0][8] = 0.7530565405876;
   fWeightMatrix1to2[0][9] = -0.591407497635599;
   fWeightMatrix1to2[0][10] = -0.7738991465563;
   fWeightMatrix1to2[0][11] = -2.34956000502218;
   fWeightMatrix1to2[0][12] = -2.32887370421828;
   fWeightMatrix1to2[0][13] = -1.3528632516011;
   fWeightMatrix1to2[0][14] = 1.6337378967284;
   fWeightMatrix1to2[0][15] = -0.908026680268497;
   fWeightMatrix1to2[0][16] = 3.53004132532025;
   fWeightMatrix1to2[0][17] = -0.327623852168891;
   fWeightMatrix1to2[0][18] = 3.5516956984728;
   fWeightMatrix1to2[0][19] = 1.22562041887073;
   fWeightMatrix1to2[0][20] = -1.16584364799144;
   fWeightMatrix1to2[0][21] = 0.459508512831272;
   fWeightMatrix1to2[0][22] = 4.22289082015629;
   fWeightMatrix1to2[0][23] = 0.669716021788557;
   fWeightMatrix1to2[0][24] = -1.35765913897309;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 20.0387992859;
   fMax_1[0][0] = 169.718002319;
   fMin_1[1][0] = 20.1175994873;
   fMax_1[1][0] = 278.061004639;
   fMin_1[2][0] = 20.0387992859;
   fMax_1[2][0] = 278.061004639;
   fMin_1[0][1] = -2.39956998825;
   fMax_1[0][1] = 2.39816999435;
   fMin_1[1][1] = -2.3845000267;
   fMax_1[1][1] = 2.39913010597;
   fMin_1[2][1] = -2.39956998825;
   fMax_1[2][1] = 2.39913010597;
   fMin_1[0][2] = -3.14141988754;
   fMax_1[0][2] = 3.14014005661;
   fMin_1[1][2] = -3.14155006409;
   fMax_1[1][2] = 3.14138007164;
   fMin_1[2][2] = -3.14155006409;
   fMax_1[2][2] = 3.14138007164;
   fMin_1[0][3] = 8.8874502182;
   fMax_1[0][3] = 81.1477966309;
   fMin_1[1][3] = 10.3790998459;
   fMax_1[1][3] = 150.102005005;
   fMin_1[2][3] = 8.8874502182;
   fMax_1[2][3] = 150.102005005;
   fMin_1[0][4] = -2.39977002144;
   fMax_1[0][4] = 2.39869999886;
   fMin_1[1][4] = -2.39748001099;
   fMax_1[1][4] = 2.39791989326;
   fMin_1[2][4] = -2.39977002144;
   fMax_1[2][4] = 2.39869999886;
   fMin_1[0][5] = -3.14139008522;
   fMax_1[0][5] = 3.13953995705;
   fMin_1[1][5] = -3.13930988312;
   fMax_1[1][5] = 3.14006996155;
   fMin_1[2][5] = -3.14139008522;
   fMax_1[2][5] = 3.14006996155;
   fMin_1[0][6] = 5.29546022415;
   fMax_1[0][6] = 58.9183998108;
   fMin_1[1][6] = 5.51318979263;
   fMax_1[1][6] = 90.4963989258;
   fMin_1[2][6] = 5.29546022415;
   fMax_1[2][6] = 90.4963989258;
   fMin_1[0][7] = -2.39901995659;
   fMax_1[0][7] = 2.398250103;
   fMin_1[1][7] = -2.39678001404;
   fMax_1[1][7] = 2.3912498951;
   fMin_1[2][7] = -2.39901995659;
   fMax_1[2][7] = 2.398250103;
   fMin_1[0][8] = -3.14122009277;
   fMax_1[0][8] = 3.14109992981;
   fMin_1[1][8] = -3.14071989059;
   fMax_1[1][8] = 3.13785004616;
   fMin_1[2][8] = -3.14122009277;
   fMax_1[2][8] = 3.14109992981;
   fMin_1[0][9] = 5.00129985809;
   fMax_1[0][9] = 40.5410003662;
   fMin_1[1][9] = 5.00728988647;
   fMax_1[1][9] = 69.7885971069;
   fMin_1[2][9] = 5.00129985809;
   fMax_1[2][9] = 69.7885971069;
   fMin_1[0][10] = -2.39884996414;
   fMax_1[0][10] = 2.39657998085;
   fMin_1[1][10] = -2.3996899128;
   fMax_1[1][10] = 2.39824008942;
   fMin_1[2][10] = -2.3996899128;
   fMax_1[2][10] = 2.39824008942;
   fMin_1[0][11] = -3.13938999176;
   fMax_1[0][11] = 3.14139008522;
   fMin_1[1][11] = -3.14139008522;
   fMax_1[1][11] = 3.1409099102;
   fMin_1[2][11] = -3.14139008522;
   fMax_1[2][11] = 3.14139008522;
   fMin_1[0][12] = -0.0301591008902;
   fMax_1[0][12] = 14.0198001862;
   fMin_1[1][12] = -0.0444267988205;
   fMax_1[1][12] = 3.01027011871;
   fMin_1[2][12] = -0.0444267988205;
   fMax_1[2][12] = 14.0198001862;
   fMin_1[0][13] = -0.0497163012624;
   fMax_1[0][13] = 1.85469996929;
   fMin_1[1][13] = -0.0540362000465;
   fMax_1[1][13] = 0.709349989891;
   fMin_1[2][13] = -0.0540362000465;
   fMax_1[2][13] = 1.85469996929;
   fMin_1[0][14] = 0.299522995949;
   fMax_1[0][14] = 96.7269973755;
   fMin_1[1][14] = 0.275514006615;
   fMax_1[1][14] = 25.4246997833;
   fMin_1[2][14] = 0.275514006615;
   fMax_1[2][14] = 96.7269973755;
   fMin_1[0][15] = 0.15038099885;
   fMax_1[0][15] = 44.9584999084;
   fMin_1[1][15] = 0.135326996446;
   fMax_1[1][15] = 6.75087022781;
   fMin_1[2][15] = 0.135326996446;
   fMax_1[2][15] = 44.9584999084;
   fMin_1[0][16] = 8.75;
   fMax_1[0][16] = 140.74899292;
   fMin_1[1][16] = 14.9264001846;
   fMax_1[1][16] = 120.709999084;
   fMin_1[2][16] = 8.75;
   fMax_1[2][16] = 140.74899292;
   fMin_1[0][17] = 12.0004997253;
   fMax_1[0][17] = 111.925003052;
   fMin_1[1][17] = 12.0264997482;
   fMax_1[1][17] = 96.6280975342;
   fMin_1[2][17] = 12.0004997253;
   fMax_1[2][17] = 111.925003052;
   fMin_1[0][18] = 110.018997192;
   fMax_1[0][18] = 164.99899292;
   fMin_1[1][18] = 110.066001892;
   fMax_1[1][18] = 164.917007446;
   fMin_1[2][18] = 110.018997192;
   fMax_1[2][18] = 164.99899292;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 19;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesGet.push_back( 11);
   indicesGet.push_back( 12);
   indicesGet.push_back( 13);
   indicesGet.push_back( 14);
   indicesGet.push_back( 15);
   indicesGet.push_back( 16);
   indicesGet.push_back( 17);
   indicesGet.push_back( 18);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);
   indicesPut.push_back( 11);
   indicesPut.push_back( 12);
   indicesPut.push_back( 13);
   indicesPut.push_back( 14);
   indicesPut.push_back( 15);
   indicesPut.push_back( 16);
   indicesPut.push_back( 17);
   indicesPut.push_back( 18);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<19;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
