// Class: ReadMLPBNN
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPBNN
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : JBochenek
Date           : Thu Apr 12 12:54:37 2012
Host           : Linux lnxthry05.hep.fsu.edu 2.6.18-238.5.1.el5 #1 SMP Fri Apr 1 18:41:58 EDT 2011 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/room2/jbochenek/HiggsCombination/TMVAfiles/TMVA-v4.1.2/test
Training events: 10000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "1200" [Number of training cycles]
HiddenLayers: "40" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "True" [Use regulator to avoid over-training]
CalculateErrors: "True" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 19
mu1_pt                        mu1_pt                        mu1_pt                        mu1_pt                                                          'F'    [20.0387992859,278.061004639]
mu1_eta                       mu1_eta                       mu1_eta                       mu1_eta                                                         'F'    [-2.39956998825,2.39913010597]
mu1_phi                       mu1_phi                       mu1_phi                       mu1_phi                                                         'F'    [-3.14155006409,3.14138007164]
mu2_pt                        mu2_pt                        mu2_pt                        mu2_pt                                                          'F'    [8.8874502182,150.102005005]
mu2_eta                       mu2_eta                       mu2_eta                       mu2_eta                                                         'F'    [-2.39977002144,2.39869999886]
mu2_phi                       mu2_phi                       mu2_phi                       mu2_phi                                                         'F'    [-3.14139008522,3.14006996155]
mu3_pt                        mu3_pt                        mu3_pt                        mu3_pt                                                          'F'    [5.29546022415,90.4963989258]
mu3_eta                       mu3_eta                       mu3_eta                       mu3_eta                                                         'F'    [-2.39901995659,2.398250103]
mu3_phi                       mu3_phi                       mu3_phi                       mu3_phi                                                         'F'    [-3.14122009277,3.14109992981]
mu4_pt                        mu4_pt                        mu4_pt                        mu4_pt                                                          'F'    [5.00129985809,69.7885971069]
mu4_eta                       mu4_eta                       mu4_eta                       mu4_eta                                                         'F'    [-2.3996899128,2.39824008942]
mu4_phi                       mu4_phi                       mu4_phi                       mu4_phi                                                         'F'    [-3.14139008522,3.14139008522]
worst_iso_X                   worst_iso_X                   worst_iso_X                   worst_iso_X                                                     'F'    [-0.0444267988205,14.0198001862]
second_worst_iso_X            second_worst_iso_X            second_worst_iso_X            second_worst_iso_X                                              'F'    [-0.0540362000465,1.85469996929]
worst_vertex                  worst_vertex                  worst_vertex                  worst_vertex                                                    'F'    [0.275514006615,96.7269973755]
second_worst_vertex           second_worst_vertex           second_worst_vertex           second_worst_vertex                                             'F'    [0.135326996446,44.9584999084]
mZ                            mZ                            mZ                            mZ                                                              'F'    [8.75,140.74899292]
mZstar                        mZstar                        mZstar                        mZstar                                                          'F'    [12.0004997253,111.925003052]
mbestH                        mbestH                        mbestH                        mbestH                                                          'F'    [110.018997192,164.99899292]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPBNN : public IClassifierReader {

 public:

   // constructor
   ReadMLPBNN( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPBNN" ),
        fNvars( 19 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "mu1_pt", "mu1_eta", "mu1_phi", "mu2_pt", "mu2_eta", "mu2_phi", "mu3_pt", "mu3_eta", "mu3_phi", "mu4_pt", "mu4_eta", "mu4_phi", "worst_iso_X", "second_worst_iso_X", "worst_vertex", "second_worst_vertex", "mZ", "mZstar", "mbestH" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 0.99999988079071;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;
      fVmin[13] = -1;
      fVmax[13] = 1;
      fVmin[14] = -1;
      fVmax[14] = 1;
      fVmin[15] = -1;
      fVmax[15] = 1;
      fVmin[16] = -1;
      fVmax[16] = 1;
      fVmin[17] = -1;
      fVmax[17] = 1;
      fVmin[18] = -1;
      fVmax[18] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPBNN() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][19];
   double fMax_1[3][19];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[19];
   double fVmax[19];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[19];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[41][20];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][41];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPBNN::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 20; fWeights[0] = new double[20]; 
   fLayerSize[1] = 41; fWeights[1] = new double[41]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.0661950417486242;
   fWeightMatrix0to1[1][0] = 0.172826944441049;
   fWeightMatrix0to1[2][0] = 0.00441027023483505;
   fWeightMatrix0to1[3][0] = 0.223699466507865;
   fWeightMatrix0to1[4][0] = -0.0606208300799825;
   fWeightMatrix0to1[5][0] = -0.0104132572740315;
   fWeightMatrix0to1[6][0] = -0.105512656912357;
   fWeightMatrix0to1[7][0] = -0.0124201529508039;
   fWeightMatrix0to1[8][0] = 0.113104792660707;
   fWeightMatrix0to1[9][0] = -0.0127988139347798;
   fWeightMatrix0to1[10][0] = -0.216780698130596;
   fWeightMatrix0to1[11][0] = -0.0150244945796528;
   fWeightMatrix0to1[12][0] = -0.154201550719321;
   fWeightMatrix0to1[13][0] = -0.0313203157861153;
   fWeightMatrix0to1[14][0] = -0.104893382968223;
   fWeightMatrix0to1[15][0] = 0.37312467686045;
   fWeightMatrix0to1[16][0] = 0.00550122749880352;
   fWeightMatrix0to1[17][0] = 0.558214896962234;
   fWeightMatrix0to1[18][0] = 0.0493002851226439;
   fWeightMatrix0to1[19][0] = -0.627469784334578;
   fWeightMatrix0to1[20][0] = 0.154416052121981;
   fWeightMatrix0to1[21][0] = 0.214135855080361;
   fWeightMatrix0to1[22][0] = 0.0345386656931087;
   fWeightMatrix0to1[23][0] = -0.281027863763193;
   fWeightMatrix0to1[24][0] = -0.267612122627248;
   fWeightMatrix0to1[25][0] = -0.150223769616881;
   fWeightMatrix0to1[26][0] = 0.0029175201941456;
   fWeightMatrix0to1[27][0] = 0.25553529113834;
   fWeightMatrix0to1[28][0] = -0.251198323202722;
   fWeightMatrix0to1[29][0] = 0.337984578162499;
   fWeightMatrix0to1[30][0] = 0.514488838722074;
   fWeightMatrix0to1[31][0] = 0.207737650944573;
   fWeightMatrix0to1[32][0] = 0.431319848826754;
   fWeightMatrix0to1[33][0] = 0.351357399458863;
   fWeightMatrix0to1[34][0] = 0.0518413782718257;
   fWeightMatrix0to1[35][0] = 0.0145617606331872;
   fWeightMatrix0to1[36][0] = 0.688768965312158;
   fWeightMatrix0to1[37][0] = 0.389751376345219;
   fWeightMatrix0to1[38][0] = 0.145952731361912;
   fWeightMatrix0to1[39][0] = -0.0179967049646963;
   fWeightMatrix0to1[0][1] = 0.468492055237068;
   fWeightMatrix0to1[1][1] = -1.33335317155564;
   fWeightMatrix0to1[2][1] = 0.00472053053374174;
   fWeightMatrix0to1[3][1] = 0.74415979153261;
   fWeightMatrix0to1[4][1] = 0.164054403137491;
   fWeightMatrix0to1[5][1] = -0.39683115154766;
   fWeightMatrix0to1[6][1] = -0.0215560930083497;
   fWeightMatrix0to1[7][1] = -0.566833989733536;
   fWeightMatrix0to1[8][1] = -0.108953275353792;
   fWeightMatrix0to1[9][1] = 0.366986907876341;
   fWeightMatrix0to1[10][1] = 0.570639624632041;
   fWeightMatrix0to1[11][1] = -0.129020111630041;
   fWeightMatrix0to1[12][1] = -0.531647430833588;
   fWeightMatrix0to1[13][1] = -0.0748031904270198;
   fWeightMatrix0to1[14][1] = -0.186988447630708;
   fWeightMatrix0to1[15][1] = -0.533777879224391;
   fWeightMatrix0to1[16][1] = 0.00212755243491049;
   fWeightMatrix0to1[17][1] = -0.261950006721297;
   fWeightMatrix0to1[18][1] = 0.0291070907950612;
   fWeightMatrix0to1[19][1] = -0.835350165378838;
   fWeightMatrix0to1[20][1] = -0.203653471363814;
   fWeightMatrix0to1[21][1] = 0.0219241744580686;
   fWeightMatrix0to1[22][1] = 0.0188125855918092;
   fWeightMatrix0to1[23][1] = -0.0166342621809914;
   fWeightMatrix0to1[24][1] = 0.387806911377524;
   fWeightMatrix0to1[25][1] = 0.316914699093425;
   fWeightMatrix0to1[26][1] = 0.72439438555965;
   fWeightMatrix0to1[27][1] = 0.808555514022013;
   fWeightMatrix0to1[28][1] = 0.775288160268729;
   fWeightMatrix0to1[29][1] = -0.094022377449518;
   fWeightMatrix0to1[30][1] = -0.0190971940287202;
   fWeightMatrix0to1[31][1] = -0.0383441544388623;
   fWeightMatrix0to1[32][1] = 0.0676632956354247;
   fWeightMatrix0to1[33][1] = -0.479190569580118;
   fWeightMatrix0to1[34][1] = 1.04245954682113;
   fWeightMatrix0to1[35][1] = -0.114567656238436;
   fWeightMatrix0to1[36][1] = -0.227903410967124;
   fWeightMatrix0to1[37][1] = -0.416287276193787;
   fWeightMatrix0to1[38][1] = 0.0326747123825902;
   fWeightMatrix0to1[39][1] = -0.00582825244364558;
   fWeightMatrix0to1[0][2] = 0.301863664672637;
   fWeightMatrix0to1[1][2] = -0.022203029270991;
   fWeightMatrix0to1[2][2] = 0.0128157130893638;
   fWeightMatrix0to1[3][2] = 0.119326195796043;
   fWeightMatrix0to1[4][2] = 0.204946729328115;
   fWeightMatrix0to1[5][2] = -0.183957634078222;
   fWeightMatrix0to1[6][2] = -0.077678346447375;
   fWeightMatrix0to1[7][2] = -0.054450737706915;
   fWeightMatrix0to1[8][2] = -0.29308244991157;
   fWeightMatrix0to1[9][2] = 0.0182118507806942;
   fWeightMatrix0to1[10][2] = -0.0570187309712271;
   fWeightMatrix0to1[11][2] = -0.256821056601528;
   fWeightMatrix0to1[12][2] = 0.201690920439183;
   fWeightMatrix0to1[13][2] = -0.0915699864227939;
   fWeightMatrix0to1[14][2] = 0.0143631951830372;
   fWeightMatrix0to1[15][2] = 0.0340505652718467;
   fWeightMatrix0to1[16][2] = 0.00564057816891625;
   fWeightMatrix0to1[17][2] = -0.472688975612973;
   fWeightMatrix0to1[18][2] = 0.0481544888092712;
   fWeightMatrix0to1[19][2] = 0.0137606318825149;
   fWeightMatrix0to1[20][2] = -0.161505854605525;
   fWeightMatrix0to1[21][2] = 0.0387274343031326;
   fWeightMatrix0to1[22][2] = 0.0340319202258266;
   fWeightMatrix0to1[23][2] = -0.0995050616880339;
   fWeightMatrix0to1[24][2] = 0.0347267202099089;
   fWeightMatrix0to1[25][2] = 0.255170612961893;
   fWeightMatrix0to1[26][2] = -0.0167401349901182;
   fWeightMatrix0to1[27][2] = -0.0488960007570424;
   fWeightMatrix0to1[28][2] = 0.0659119109088061;
   fWeightMatrix0to1[29][2] = 0.24748620636941;
   fWeightMatrix0to1[30][2] = -0.357905416379648;
   fWeightMatrix0to1[31][2] = -0.0523332825809894;
   fWeightMatrix0to1[32][2] = 0.124080225811001;
   fWeightMatrix0to1[33][2] = -0.0546239384734484;
   fWeightMatrix0to1[34][2] = -0.128029177172508;
   fWeightMatrix0to1[35][2] = 0.00912511780603732;
   fWeightMatrix0to1[36][2] = 0.21006507469384;
   fWeightMatrix0to1[37][2] = -0.155414731115412;
   fWeightMatrix0to1[38][2] = 0.0280301189147536;
   fWeightMatrix0to1[39][2] = -0.015071090879195;
   fWeightMatrix0to1[0][3] = 0.00838970194242121;
   fWeightMatrix0to1[1][3] = 0.0243122977950822;
   fWeightMatrix0to1[2][3] = 0.0041641527030659;
   fWeightMatrix0to1[3][3] = 0.00868932129252629;
   fWeightMatrix0to1[4][3] = -0.0388860613249981;
   fWeightMatrix0to1[5][3] = -0.0160399478768925;
   fWeightMatrix0to1[6][3] = 0.0216668482814634;
   fWeightMatrix0to1[7][3] = 0.0166242701483331;
   fWeightMatrix0to1[8][3] = 0.0532539781790403;
   fWeightMatrix0to1[9][3] = 0.000363794020734245;
   fWeightMatrix0to1[10][3] = 0.0800438329474308;
   fWeightMatrix0to1[11][3] = -0.0359492080627949;
   fWeightMatrix0to1[12][3] = -0.0883150417970145;
   fWeightMatrix0to1[13][3] = -0.0130794568188558;
   fWeightMatrix0to1[14][3] = 0.0200081244627373;
   fWeightMatrix0to1[15][3] = 0.0582841712940384;
   fWeightMatrix0to1[16][3] = 0.00283265013847061;
   fWeightMatrix0to1[17][3] = 0.0762553221046134;
   fWeightMatrix0to1[18][3] = 0.0164601564516653;
   fWeightMatrix0to1[19][3] = -0.00320734682329507;
   fWeightMatrix0to1[20][3] = 0.00506941924452391;
   fWeightMatrix0to1[21][3] = 0.0654024178580714;
   fWeightMatrix0to1[22][3] = 0.00921354570676866;
   fWeightMatrix0to1[23][3] = 0.0119531147010245;
   fWeightMatrix0to1[24][3] = 0.068207515036107;
   fWeightMatrix0to1[25][3] = -0.00671908940695527;
   fWeightMatrix0to1[26][3] = 0.0109455883936686;
   fWeightMatrix0to1[27][3] = -0.0850630613601703;
   fWeightMatrix0to1[28][3] = 0.0824498226667296;
   fWeightMatrix0to1[29][3] = -0.0138270159379876;
   fWeightMatrix0to1[30][3] = -0.0970397834058691;
   fWeightMatrix0to1[31][3] = -0.0120168803951049;
   fWeightMatrix0to1[32][3] = 0.0417595969313935;
   fWeightMatrix0to1[33][3] = -0.0158469102796627;
   fWeightMatrix0to1[34][3] = -0.0393740641920108;
   fWeightMatrix0to1[35][3] = 0.0734783610885259;
   fWeightMatrix0to1[36][3] = 0.0887766047949961;
   fWeightMatrix0to1[37][3] = -0.00731479179728747;
   fWeightMatrix0to1[38][3] = -1.6854298845279e-05;
   fWeightMatrix0to1[39][3] = -0.00544326097160764;
   fWeightMatrix0to1[0][4] = 0.208484822232814;
   fWeightMatrix0to1[1][4] = 1.10924684314692;
   fWeightMatrix0to1[2][4] = 0.00154009689084898;
   fWeightMatrix0to1[3][4] = -0.653946527716615;
   fWeightMatrix0to1[4][4] = 0.268927997713271;
   fWeightMatrix0to1[5][4] = 1.29383602141481;
   fWeightMatrix0to1[6][4] = -0.371415507855307;
   fWeightMatrix0to1[7][4] = 1.12154614213665;
   fWeightMatrix0to1[8][4] = 0.673785093366318;
   fWeightMatrix0to1[9][4] = -0.223768087460044;
   fWeightMatrix0to1[10][4] = 0.461225183062394;
   fWeightMatrix0to1[11][4] = -0.184044712906601;
   fWeightMatrix0to1[12][4] = -0.598291082495117;
   fWeightMatrix0to1[13][4] = -0.217104301189174;
   fWeightMatrix0to1[14][4] = -0.179262790627873;
   fWeightMatrix0to1[15][4] = -0.365297571100875;
   fWeightMatrix0to1[16][4] = 0.0049742284656603;
   fWeightMatrix0to1[17][4] = 0.489016501040711;
   fWeightMatrix0to1[18][4] = 0.0177854682012782;
   fWeightMatrix0to1[19][4] = -0.418807165555612;
   fWeightMatrix0to1[20][4] = -0.25926726224935;
   fWeightMatrix0to1[21][4] = 0.755850149801842;
   fWeightMatrix0to1[22][4] = 0.0385355360753306;
   fWeightMatrix0to1[23][4] = -1.56588601497031;
   fWeightMatrix0to1[24][4] = -0.447452218383788;
   fWeightMatrix0to1[25][4] = -0.00668748287509832;
   fWeightMatrix0to1[26][4] = -0.393605435403101;
   fWeightMatrix0to1[27][4] = 1.12524333336801;
   fWeightMatrix0to1[28][4] = 1.31148495372749;
   fWeightMatrix0to1[29][4] = 0.521773650764736;
   fWeightMatrix0to1[30][4] = 0.199075822010294;
   fWeightMatrix0to1[31][4] = 0.64890746145702;
   fWeightMatrix0to1[32][4] = 0.394992822995073;
   fWeightMatrix0to1[33][4] = -0.641635429985034;
   fWeightMatrix0to1[34][4] = 0.324715292693836;
   fWeightMatrix0to1[35][4] = -0.0676189070843197;
   fWeightMatrix0to1[36][4] = -0.384055447870042;
   fWeightMatrix0to1[37][4] = -0.664394620376154;
   fWeightMatrix0to1[38][4] = -0.0410297418197197;
   fWeightMatrix0to1[39][4] = -0.0086492040474734;
   fWeightMatrix0to1[0][5] = 0.0477558390040977;
   fWeightMatrix0to1[1][5] = -0.0710568522274685;
   fWeightMatrix0to1[2][5] = 0.0140395820280787;
   fWeightMatrix0to1[3][5] = -0.024229788181568;
   fWeightMatrix0to1[4][5] = 0.120365426281339;
   fWeightMatrix0to1[5][5] = -0.00766201598957401;
   fWeightMatrix0to1[6][5] = -0.039862513443395;
   fWeightMatrix0to1[7][5] = -0.0605853871344397;
   fWeightMatrix0to1[8][5] = -0.0974179300428635;
   fWeightMatrix0to1[9][5] = -0.0222128469824793;
   fWeightMatrix0to1[10][5] = -0.0544216129072035;
   fWeightMatrix0to1[11][5] = 0.184471472425923;
   fWeightMatrix0to1[12][5] = -0.151029405317376;
   fWeightMatrix0to1[13][5] = -0.0108864650497177;
   fWeightMatrix0to1[14][5] = 0.0234906409182114;
   fWeightMatrix0to1[15][5] = -0.242640888560556;
   fWeightMatrix0to1[16][5] = 0.00579526371670127;
   fWeightMatrix0to1[17][5] = 0.392329913793834;
   fWeightMatrix0to1[18][5] = 0.0136517299849626;
   fWeightMatrix0to1[19][5] = -0.176215057588025;
   fWeightMatrix0to1[20][5] = -0.109779400238754;
   fWeightMatrix0to1[21][5] = -0.263652056497317;
   fWeightMatrix0to1[22][5] = 0.028507499223977;
   fWeightMatrix0to1[23][5] = 0.195868768950769;
   fWeightMatrix0to1[24][5] = 0.0742411299465262;
   fWeightMatrix0to1[25][5] = -0.478400918576088;
   fWeightMatrix0to1[26][5] = 0.14911283504864;
   fWeightMatrix0to1[27][5] = -0.0669778632000585;
   fWeightMatrix0to1[28][5] = -0.0220497579977738;
   fWeightMatrix0to1[29][5] = -0.195602147761573;
   fWeightMatrix0to1[30][5] = 0.515128085991114;
   fWeightMatrix0to1[31][5] = 0.279379991007665;
   fWeightMatrix0to1[32][5] = 0.0947719009463974;
   fWeightMatrix0to1[33][5] = -0.0451127430300716;
   fWeightMatrix0to1[34][5] = 0.212284322280481;
   fWeightMatrix0to1[35][5] = 0.0717220047924978;
   fWeightMatrix0to1[36][5] = 0.0136227611348584;
   fWeightMatrix0to1[37][5] = 0.0837995660486602;
   fWeightMatrix0to1[38][5] = -0.0178237510276634;
   fWeightMatrix0to1[39][5] = -0.0139552636507958;
   fWeightMatrix0to1[0][6] = 0.149664190408673;
   fWeightMatrix0to1[1][6] = -0.157843995664375;
   fWeightMatrix0to1[2][6] = 0.00682723661337452;
   fWeightMatrix0to1[3][6] = 0.0672481845852698;
   fWeightMatrix0to1[4][6] = -0.178764561440812;
   fWeightMatrix0to1[5][6] = -0.0456772281905653;
   fWeightMatrix0to1[6][6] = 0.13943854078417;
   fWeightMatrix0to1[7][6] = -0.248754667188946;
   fWeightMatrix0to1[8][6] = 0.050601307175121;
   fWeightMatrix0to1[9][6] = -0.0492905669481251;
   fWeightMatrix0to1[10][6] = 0.104976871239938;
   fWeightMatrix0to1[11][6] = -0.0623249467856842;
   fWeightMatrix0to1[12][6] = -0.0646352043012058;
   fWeightMatrix0to1[13][6] = 0.0295500993312884;
   fWeightMatrix0to1[14][6] = 0.197782836027324;
   fWeightMatrix0to1[15][6] = 0.564125641531482;
   fWeightMatrix0to1[16][6] = 0.0033993992311105;
   fWeightMatrix0to1[17][6] = -0.262581001541818;
   fWeightMatrix0to1[18][6] = 0.0376395673539711;
   fWeightMatrix0to1[19][6] = -0.18604304744964;
   fWeightMatrix0to1[20][6] = 0.11710944936629;
   fWeightMatrix0to1[21][6] = 0.143568320972176;
   fWeightMatrix0to1[22][6] = 0.0178489518545396;
   fWeightMatrix0to1[23][6] = 0.240276426381888;
   fWeightMatrix0to1[24][6] = 0.0696756745732935;
   fWeightMatrix0to1[25][6] = 0.207722258891525;
   fWeightMatrix0to1[26][6] = -0.299858406712247;
   fWeightMatrix0to1[27][6] = 0.100526170739576;
   fWeightMatrix0to1[28][6] = 0.0635139218397923;
   fWeightMatrix0to1[29][6] = 0.0971303369040982;
   fWeightMatrix0to1[30][6] = 0.0786665047695999;
   fWeightMatrix0to1[31][6] = 0.0821427493887128;
   fWeightMatrix0to1[32][6] = 0.0437793454981312;
   fWeightMatrix0to1[33][6] = -0.229178569872747;
   fWeightMatrix0to1[34][6] = -0.121517189898956;
   fWeightMatrix0to1[35][6] = 0.456963234323172;
   fWeightMatrix0to1[36][6] = 0.0950565101505704;
   fWeightMatrix0to1[37][6] = 0.152777407757856;
   fWeightMatrix0to1[38][6] = 0.286179144423498;
   fWeightMatrix0to1[39][6] = -0.00972053051211664;
   fWeightMatrix0to1[0][7] = 0.642087222739815;
   fWeightMatrix0to1[1][7] = 0.130404292465183;
   fWeightMatrix0to1[2][7] = 0.00625771866841166;
   fWeightMatrix0to1[3][7] = 0.0226612329397484;
   fWeightMatrix0to1[4][7] = -2.38752873275676;
   fWeightMatrix0to1[5][7] = -0.585171212078969;
   fWeightMatrix0to1[6][7] = -0.721826145412052;
   fWeightMatrix0to1[7][7] = 0.858666431587473;
   fWeightMatrix0to1[8][7] = -0.360794182691218;
   fWeightMatrix0to1[9][7] = 0.131277790820283;
   fWeightMatrix0to1[10][7] = -1.3703523810712;
   fWeightMatrix0to1[11][7] = -0.725201980325408;
   fWeightMatrix0to1[12][7] = -0.107572664544789;
   fWeightMatrix0to1[13][7] = 0.164424649229166;
   fWeightMatrix0to1[14][7] = 0.100064345533432;
   fWeightMatrix0to1[15][7] = -0.336807588403939;
   fWeightMatrix0to1[16][7] = 0.00163005644053316;
   fWeightMatrix0to1[17][7] = -0.560207045491169;
   fWeightMatrix0to1[18][7] = 0.0581719245443511;
   fWeightMatrix0to1[19][7] = -0.40986673050097;
   fWeightMatrix0to1[20][7] = -1.17833175280631;
   fWeightMatrix0to1[21][7] = 0.489291045449248;
   fWeightMatrix0to1[22][7] = 0.00890742001268389;
   fWeightMatrix0to1[23][7] = -0.759917164461312;
   fWeightMatrix0to1[24][7] = 0.0509202695986613;
   fWeightMatrix0to1[25][7] = -0.570758146692582;
   fWeightMatrix0to1[26][7] = -0.99450002157783;
   fWeightMatrix0to1[27][7] = -1.12211745714108;
   fWeightMatrix0to1[28][7] = -0.472323583548433;
   fWeightMatrix0to1[29][7] = -1.63567638783701;
   fWeightMatrix0to1[30][7] = -0.0189991485248761;
   fWeightMatrix0to1[31][7] = -0.399947986194757;
   fWeightMatrix0to1[32][7] = -1.00701265806453;
   fWeightMatrix0to1[33][7] = 1.11625168200698;
   fWeightMatrix0to1[34][7] = 0.382366534621188;
   fWeightMatrix0to1[35][7] = 0.165503621365314;
   fWeightMatrix0to1[36][7] = -0.0959947443004367;
   fWeightMatrix0to1[37][7] = -0.603193666379897;
   fWeightMatrix0to1[38][7] = 1.61145904161665;
   fWeightMatrix0to1[39][7] = -0.00817209657337105;
   fWeightMatrix0to1[0][8] = 0.00249141891039763;
   fWeightMatrix0to1[1][8] = 0.00130134461863879;
   fWeightMatrix0to1[2][8] = 4.49563356211427e-05;
   fWeightMatrix0to1[3][8] = 0.000184214074594771;
   fWeightMatrix0to1[4][8] = 0.000614658677295996;
   fWeightMatrix0to1[5][8] = 0.000177797775476186;
   fWeightMatrix0to1[6][8] = 0.00235880107879058;
   fWeightMatrix0to1[7][8] = 0.00209436382430667;
   fWeightMatrix0to1[8][8] = -0.00118766828831849;
   fWeightMatrix0to1[9][8] = 0.000549198349163289;
   fWeightMatrix0to1[10][8] = -0.00330527581693432;
   fWeightMatrix0to1[11][8] = -0.00221650465896893;
   fWeightMatrix0to1[12][8] = 0.00539331420547785;
   fWeightMatrix0to1[13][8] = -0.000972956042246544;
   fWeightMatrix0to1[14][8] = 0.00160867276451298;
   fWeightMatrix0to1[15][8] = 0.00169443759767809;
   fWeightMatrix0to1[16][8] = 5.34137298574662e-08;
   fWeightMatrix0to1[17][8] = 0.00463694969333876;
   fWeightMatrix0to1[18][8] = -0.000111525385827403;
   fWeightMatrix0to1[19][8] = -0.00233666127288735;
   fWeightMatrix0to1[20][8] = 0.000894800877100028;
   fWeightMatrix0to1[21][8] = 0.00434486331476738;
   fWeightMatrix0to1[22][8] = -3.9188630057381e-05;
   fWeightMatrix0to1[23][8] = 0.0031694141783878;
   fWeightMatrix0to1[24][8] = -0.000371429841839764;
   fWeightMatrix0to1[25][8] = 0.000688454834941795;
   fWeightMatrix0to1[26][8] = -0.003283315774583;
   fWeightMatrix0to1[27][8] = 0.000431696908220325;
   fWeightMatrix0to1[28][8] = 0.00265374709044983;
   fWeightMatrix0to1[29][8] = -0.00220085599061594;
   fWeightMatrix0to1[30][8] = 0.00301724504964494;
   fWeightMatrix0to1[31][8] = -0.00340367972036685;
   fWeightMatrix0to1[32][8] = -0.000197832647317334;
   fWeightMatrix0to1[33][8] = -0.00349345518692314;
   fWeightMatrix0to1[34][8] = -0.00151512016883512;
   fWeightMatrix0to1[35][8] = -0.000883022191669471;
   fWeightMatrix0to1[36][8] = 0.000838923270218557;
   fWeightMatrix0to1[37][8] = -0.000380620439057397;
   fWeightMatrix0to1[38][8] = 1.44277528535469e-05;
   fWeightMatrix0to1[39][8] = 4.7261093161141e-05;
   fWeightMatrix0to1[0][9] = 0.115683665438915;
   fWeightMatrix0to1[1][9] = -0.0364923456987703;
   fWeightMatrix0to1[2][9] = -0.00584942739199506;
   fWeightMatrix0to1[3][9] = -0.261457802505341;
   fWeightMatrix0to1[4][9] = 0.128381722826178;
   fWeightMatrix0to1[5][9] = -0.1542936519587;
   fWeightMatrix0to1[6][9] = -0.551861681331239;
   fWeightMatrix0to1[7][9] = -0.186234320985324;
   fWeightMatrix0to1[8][9] = -0.0026656566759625;
   fWeightMatrix0to1[9][9] = -0.404358727684441;
   fWeightMatrix0to1[10][9] = -0.037733352091734;
   fWeightMatrix0to1[11][9] = -0.0874857303907242;
   fWeightMatrix0to1[12][9] = 0.183406408969483;
   fWeightMatrix0to1[13][9] = 0.122730808598781;
   fWeightMatrix0to1[14][9] = 0.150237751886222;
   fWeightMatrix0to1[15][9] = 0.734346071519763;
   fWeightMatrix0to1[16][9] = 0.00284352314280325;
   fWeightMatrix0to1[17][9] = -0.366448858270406;
   fWeightMatrix0to1[18][9] = 0.00709274912774914;
   fWeightMatrix0to1[19][9] = 0.949294795681177;
   fWeightMatrix0to1[20][9] = 0.378236268598456;
   fWeightMatrix0to1[21][9] = 0.961474285093099;
   fWeightMatrix0to1[22][9] = 0.00210041234152967;
   fWeightMatrix0to1[23][9] = -0.0771922763095115;
   fWeightMatrix0to1[24][9] = 0.196631861225926;
   fWeightMatrix0to1[25][9] = 0.280123768651844;
   fWeightMatrix0to1[26][9] = -0.383753452992973;
   fWeightMatrix0to1[27][9] = -0.395462456044858;
   fWeightMatrix0to1[28][9] = 0.0251885572866734;
   fWeightMatrix0to1[29][9] = -0.174754444363029;
   fWeightMatrix0to1[30][9] = -0.0453943842259465;
   fWeightMatrix0to1[31][9] = 0.0511359737934431;
   fWeightMatrix0to1[32][9] = -0.178150907715001;
   fWeightMatrix0to1[33][9] = -0.635064197672031;
   fWeightMatrix0to1[34][9] = -0.0532903603986;
   fWeightMatrix0to1[35][9] = 0.478870498287998;
   fWeightMatrix0to1[36][9] = 0.261146693386139;
   fWeightMatrix0to1[37][9] = 0.091942599554257;
   fWeightMatrix0to1[38][9] = 0.16939337767552;
   fWeightMatrix0to1[39][9] = -0.0110232597055131;
   fWeightMatrix0to1[0][10] = 0.150075517040446;
   fWeightMatrix0to1[1][10] = 0.262575790662185;
   fWeightMatrix0to1[2][10] = 0.00564656096943094;
   fWeightMatrix0to1[3][10] = 1.0686568411064;
   fWeightMatrix0to1[4][10] = 0.595689703287695;
   fWeightMatrix0to1[5][10] = -0.537513656464065;
   fWeightMatrix0to1[6][10] = -0.25029365835903;
   fWeightMatrix0to1[7][10] = 0.191253024659037;
   fWeightMatrix0to1[8][10] = 0.128027920807911;
   fWeightMatrix0to1[9][10] = -0.44266258006474;
   fWeightMatrix0to1[10][10] = 0.793528635104566;
   fWeightMatrix0to1[11][10] = -0.0720145109609885;
   fWeightMatrix0to1[12][10] = 1.03739263872365;
   fWeightMatrix0to1[13][10] = -0.28375795599677;
   fWeightMatrix0to1[14][10] = 0.184166392429439;
   fWeightMatrix0to1[15][10] = 0.344340645561919;
   fWeightMatrix0to1[16][10] = 0.00830373216765095;
   fWeightMatrix0to1[17][10] = -0.0341041997382106;
   fWeightMatrix0to1[18][10] = -0.0631029419961454;
   fWeightMatrix0to1[19][10] = -0.039842744471623;
   fWeightMatrix0to1[20][10] = 0.414068538542417;
   fWeightMatrix0to1[21][10] = 0.0540425915089916;
   fWeightMatrix0to1[22][10] = 0.0630780801795375;
   fWeightMatrix0to1[23][10] = -0.177013173885768;
   fWeightMatrix0to1[24][10] = 0.247203019618704;
   fWeightMatrix0to1[25][10] = 0.033345490457651;
   fWeightMatrix0to1[26][10] = -0.393298553448477;
   fWeightMatrix0to1[27][10] = 0.33114815669066;
   fWeightMatrix0to1[28][10] = -0.484064639285097;
   fWeightMatrix0to1[29][10] = 0.111801551989058;
   fWeightMatrix0to1[30][10] = -0.782464920754787;
   fWeightMatrix0to1[31][10] = -0.712407549426651;
   fWeightMatrix0to1[32][10] = 0.636277682551752;
   fWeightMatrix0to1[33][10] = 0.440302481728338;
   fWeightMatrix0to1[34][10] = 0.595057151624944;
   fWeightMatrix0to1[35][10] = 0.0973851624611938;
   fWeightMatrix0to1[36][10] = -0.116413856883534;
   fWeightMatrix0to1[37][10] = 1.46055486608703;
   fWeightMatrix0to1[38][10] = -1.15258067428504;
   fWeightMatrix0to1[39][10] = -0.0259409034012143;
   fWeightMatrix0to1[0][11] = -0.00050846903285862;
   fWeightMatrix0to1[1][11] = -0.000871369630590871;
   fWeightMatrix0to1[2][11] = -5.2748913972546e-05;
   fWeightMatrix0to1[3][11] = 4.84589112145916e-05;
   fWeightMatrix0to1[4][11] = 0.000912197228925125;
   fWeightMatrix0to1[5][11] = 0.000453759888777442;
   fWeightMatrix0to1[6][11] = -0.0012475024816296;
   fWeightMatrix0to1[7][11] = 0.000399797659180465;
   fWeightMatrix0to1[8][11] = -2.99009034040319e-05;
   fWeightMatrix0to1[9][11] = -0.000505252020382645;
   fWeightMatrix0to1[10][11] = 0.00042180785901341;
   fWeightMatrix0to1[11][11] = 0.000575950482347311;
   fWeightMatrix0to1[12][11] = 8.50117914405214e-05;
   fWeightMatrix0to1[13][11] = 0.000168016874334111;
   fWeightMatrix0to1[14][11] = 0.000260987123648422;
   fWeightMatrix0to1[15][11] = -0.000408008818996392;
   fWeightMatrix0to1[16][11] = -2.42732884178987e-05;
   fWeightMatrix0to1[17][11] = -0.00105604617068001;
   fWeightMatrix0to1[18][11] = -0.000241125752121121;
   fWeightMatrix0to1[19][11] = -0.000104535913755673;
   fWeightMatrix0to1[20][11] = -0.000826462291188341;
   fWeightMatrix0to1[21][11] = -3.36524080584851e-05;
   fWeightMatrix0to1[22][11] = -0.000138323723872665;
   fWeightMatrix0to1[23][11] = -0.000314882952328335;
   fWeightMatrix0to1[24][11] = -0.000217910402782363;
   fWeightMatrix0to1[25][11] = 0.00179270307158253;
   fWeightMatrix0to1[26][11] = 0.00127500074830651;
   fWeightMatrix0to1[27][11] = 0.000943897136423713;
   fWeightMatrix0to1[28][11] = -0.00116941805411793;
   fWeightMatrix0to1[29][11] = -0.00130080297968487;
   fWeightMatrix0to1[30][11] = 0.000533076060364866;
   fWeightMatrix0to1[31][11] = 0.000258416728783822;
   fWeightMatrix0to1[32][11] = -0.00112823919177229;
   fWeightMatrix0to1[33][11] = 0.000580675076724308;
   fWeightMatrix0to1[34][11] = 0.000300055279493936;
   fWeightMatrix0to1[35][11] = 0.000733566882498493;
   fWeightMatrix0to1[36][11] = -0.000518567850649481;
   fWeightMatrix0to1[37][11] = -0.000868311814851781;
   fWeightMatrix0to1[38][11] = -0.00108267963927644;
   fWeightMatrix0to1[39][11] = 6.25408832044201e-05;
   fWeightMatrix0to1[0][12] = -0.37599187917005;
   fWeightMatrix0to1[1][12] = 0.293834574261212;
   fWeightMatrix0to1[2][12] = 0.185889032849968;
   fWeightMatrix0to1[3][12] = -0.103623736819157;
   fWeightMatrix0to1[4][12] = 0.131155027123914;
   fWeightMatrix0to1[5][12] = 0.584267015793593;
   fWeightMatrix0to1[6][12] = 0.00214044715191415;
   fWeightMatrix0to1[7][12] = -0.250625046069682;
   fWeightMatrix0to1[8][12] = -0.0460577427368605;
   fWeightMatrix0to1[9][12] = -0.433100617534811;
   fWeightMatrix0to1[10][12] = -0.222603357460319;
   fWeightMatrix0to1[11][12] = -0.326480220963515;
   fWeightMatrix0to1[12][12] = -0.766304347916402;
   fWeightMatrix0to1[13][12] = -0.468581161889903;
   fWeightMatrix0to1[14][12] = 1.5457985259405;
   fWeightMatrix0to1[15][12] = -0.380220755806196;
   fWeightMatrix0to1[16][12] = 0.120466020164984;
   fWeightMatrix0to1[17][12] = -0.554573657670972;
   fWeightMatrix0to1[18][12] = 0.276361899905831;
   fWeightMatrix0to1[19][12] = -0.080767176051627;
   fWeightMatrix0to1[20][12] = -0.237560409991943;
   fWeightMatrix0to1[21][12] = 1.41130760675644;
   fWeightMatrix0to1[22][12] = 0.213421153364476;
   fWeightMatrix0to1[23][12] = -0.0613800134823876;
   fWeightMatrix0to1[24][12] = -2.26916061756156;
   fWeightMatrix0to1[25][12] = -0.332890503707351;
   fWeightMatrix0to1[26][12] = 0.903080679446948;
   fWeightMatrix0to1[27][12] = -0.217744422182287;
   fWeightMatrix0to1[28][12] = 0.218001260221775;
   fWeightMatrix0to1[29][12] = -0.633056332916877;
   fWeightMatrix0to1[30][12] = 0.860071102485899;
   fWeightMatrix0to1[31][12] = 0.127248941313936;
   fWeightMatrix0to1[32][12] = -0.110537246024105;
   fWeightMatrix0to1[33][12] = -0.113998083950459;
   fWeightMatrix0to1[34][12] = 0.366239471044557;
   fWeightMatrix0to1[35][12] = 0.379118829365095;
   fWeightMatrix0to1[36][12] = -0.494708936467636;
   fWeightMatrix0to1[37][12] = 0.541182480150438;
   fWeightMatrix0to1[38][12] = -0.0336301631777375;
   fWeightMatrix0to1[39][12] = -0.013758035966183;
   fWeightMatrix0to1[0][13] = 0.0389070911201519;
   fWeightMatrix0to1[1][13] = -0.0120377635747113;
   fWeightMatrix0to1[2][13] = 0.00565662647044789;
   fWeightMatrix0to1[3][13] = -0.0661581978965319;
   fWeightMatrix0to1[4][13] = -0.630761331395424;
   fWeightMatrix0to1[5][13] = -0.139076683289039;
   fWeightMatrix0to1[6][13] = -0.442869820212701;
   fWeightMatrix0to1[7][13] = 0.358892279700438;
   fWeightMatrix0to1[8][13] = 0.818960856297271;
   fWeightMatrix0to1[9][13] = -0.155462100031727;
   fWeightMatrix0to1[10][13] = -0.288520736590164;
   fWeightMatrix0to1[11][13] = -0.326940426152728;
   fWeightMatrix0to1[12][13] = 0.537279114421412;
   fWeightMatrix0to1[13][13] = -0.178717441924401;
   fWeightMatrix0to1[14][13] = 0.682978726744392;
   fWeightMatrix0to1[15][13] = 0.509140039265646;
   fWeightMatrix0to1[16][13] = 0.00881215695561271;
   fWeightMatrix0to1[17][13] = 0.0381782215342885;
   fWeightMatrix0to1[18][13] = -0.00772264499422982;
   fWeightMatrix0to1[19][13] = -0.0512753408972506;
   fWeightMatrix0to1[20][13] = -0.087780748910289;
   fWeightMatrix0to1[21][13] = 0.0544829644372827;
   fWeightMatrix0to1[22][13] = 0.1021402865275;
   fWeightMatrix0to1[23][13] = 0.462782920874868;
   fWeightMatrix0to1[24][13] = -1.23181279527419;
   fWeightMatrix0to1[25][13] = 0.470838057127352;
   fWeightMatrix0to1[26][13] = -0.280646355402527;
   fWeightMatrix0to1[27][13] = -0.507574074858303;
   fWeightMatrix0to1[28][13] = -0.119431911932584;
   fWeightMatrix0to1[29][13] = 0.133997651323538;
   fWeightMatrix0to1[30][13] = 0.559426215767534;
   fWeightMatrix0to1[31][13] = -0.0375735094017938;
   fWeightMatrix0to1[32][13] = 0.249616293470794;
   fWeightMatrix0to1[33][13] = 0.0254192896080727;
   fWeightMatrix0to1[34][13] = -0.458777269641297;
   fWeightMatrix0to1[35][13] = 0.345532776257108;
   fWeightMatrix0to1[36][13] = -0.832372735950097;
   fWeightMatrix0to1[37][13] = 0.0121857330351543;
   fWeightMatrix0to1[38][13] = 0.182926309241334;
   fWeightMatrix0to1[39][13] = -0.0483833350574274;
   fWeightMatrix0to1[0][14] = 0.447258994627227;
   fWeightMatrix0to1[1][14] = -0.520912609161116;
   fWeightMatrix0to1[2][14] = 0.404284336708713;
   fWeightMatrix0to1[3][14] = 0.0777575550277487;
   fWeightMatrix0to1[4][14] = -0.0543861552650188;
   fWeightMatrix0to1[5][14] = -0.833096859525547;
   fWeightMatrix0to1[6][14] = -0.766475118110285;
   fWeightMatrix0to1[7][14] = -1.36862343135399;
   fWeightMatrix0to1[8][14] = -0.621401953187721;
   fWeightMatrix0to1[9][14] = -0.920005060386895;
   fWeightMatrix0to1[10][14] = 0.668816892296375;
   fWeightMatrix0to1[11][14] = -0.0179593463275316;
   fWeightMatrix0to1[12][14] = -0.457987330594919;
   fWeightMatrix0to1[13][14] = 0.419909031177015;
   fWeightMatrix0to1[14][14] = -0.0406947119334017;
   fWeightMatrix0to1[15][14] = -1.42046396271788;
   fWeightMatrix0to1[16][14] = 0.187075950083641;
   fWeightMatrix0to1[17][14] = -0.237572615430618;
   fWeightMatrix0to1[18][14] = 0.438747912714529;
   fWeightMatrix0to1[19][14] = -1.39671961600928;
   fWeightMatrix0to1[20][14] = 0.382269574407984;
   fWeightMatrix0to1[21][14] = -2.40622838441913;
   fWeightMatrix0to1[22][14] = 0.321642163009097;
   fWeightMatrix0to1[23][14] = -1.08317356100971;
   fWeightMatrix0to1[24][14] = -1.92335077159184;
   fWeightMatrix0to1[25][14] = -0.94014594157104;
   fWeightMatrix0to1[26][14] = 0.409185821490462;
   fWeightMatrix0to1[27][14] = 0.319721694409571;
   fWeightMatrix0to1[28][14] = -0.796555092830107;
   fWeightMatrix0to1[29][14] = -0.191510344973674;
   fWeightMatrix0to1[30][14] = -0.607814356377459;
   fWeightMatrix0to1[31][14] = 0.189126490238151;
   fWeightMatrix0to1[32][14] = 0.370778262773941;
   fWeightMatrix0to1[33][14] = 0.584740044043531;
   fWeightMatrix0to1[34][14] = -0.922577538294954;
   fWeightMatrix0to1[35][14] = 0.816063981123406;
   fWeightMatrix0to1[36][14] = 1.01994067997383;
   fWeightMatrix0to1[37][14] = -1.10501072369589;
   fWeightMatrix0to1[38][14] = 0.493850152344446;
   fWeightMatrix0to1[39][14] = -0.310090400480763;
   fWeightMatrix0to1[0][15] = -0.0241769980565375;
   fWeightMatrix0to1[1][15] = 0.211128082244764;
   fWeightMatrix0to1[2][15] = 0.0130790879487954;
   fWeightMatrix0to1[3][15] = 0.195562418225575;
   fWeightMatrix0to1[4][15] = 0.0705237923150445;
   fWeightMatrix0to1[5][15] = 0.1894325115799;
   fWeightMatrix0to1[6][15] = -0.194529003315105;
   fWeightMatrix0to1[7][15] = 0.273246980407362;
   fWeightMatrix0to1[8][15] = 0.165697136143673;
   fWeightMatrix0to1[9][15] = -0.0539972024592067;
   fWeightMatrix0to1[10][15] = -0.274145345949724;
   fWeightMatrix0to1[11][15] = -0.0867925867602194;
   fWeightMatrix0to1[12][15] = -0.0406787906383847;
   fWeightMatrix0to1[13][15] = -0.0327421047049085;
   fWeightMatrix0to1[14][15] = -0.278160732930788;
   fWeightMatrix0to1[15][15] = 0.0412256123478031;
   fWeightMatrix0to1[16][15] = 0.012000682916029;
   fWeightMatrix0to1[17][15] = -0.0532866080446955;
   fWeightMatrix0to1[18][15] = 0.0535100203250956;
   fWeightMatrix0to1[19][15] = -0.153233635293475;
   fWeightMatrix0to1[20][15] = 0.0544089431005029;
   fWeightMatrix0to1[21][15] = -0.487403918461459;
   fWeightMatrix0to1[22][15] = 0.0647815209532057;
   fWeightMatrix0to1[23][15] = -0.0209827845990457;
   fWeightMatrix0to1[24][15] = 0.163910176722897;
   fWeightMatrix0to1[25][15] = -0.0541671755791274;
   fWeightMatrix0to1[26][15] = 0.322810206526216;
   fWeightMatrix0to1[27][15] = 0.178994092831892;
   fWeightMatrix0to1[28][15] = -0.25295821678157;
   fWeightMatrix0to1[29][15] = -0.246553133840851;
   fWeightMatrix0to1[30][15] = 0.381951165658053;
   fWeightMatrix0to1[31][15] = 0.166831415480201;
   fWeightMatrix0to1[32][15] = 0.0538015680462056;
   fWeightMatrix0to1[33][15] = 0.145180027689569;
   fWeightMatrix0to1[34][15] = -0.285219595993856;
   fWeightMatrix0to1[35][15] = 0.209961543667807;
   fWeightMatrix0to1[36][15] = 0.174165730103176;
   fWeightMatrix0to1[37][15] = -0.00202522738044995;
   fWeightMatrix0to1[38][15] = -0.0869951370750389;
   fWeightMatrix0to1[39][15] = -0.0365322182722143;
   fWeightMatrix0to1[0][16] = -0.0980021177162849;
   fWeightMatrix0to1[1][16] = 0.810971099100352;
   fWeightMatrix0to1[2][16] = 0.0173180977323898;
   fWeightMatrix0to1[3][16] = 0.358388046793463;
   fWeightMatrix0to1[4][16] = -0.199931161432275;
   fWeightMatrix0to1[5][16] = -0.556433999832736;
   fWeightMatrix0to1[6][16] = -0.0546921759142997;
   fWeightMatrix0to1[7][16] = -0.963367063303282;
   fWeightMatrix0to1[8][16] = 0.313057921382819;
   fWeightMatrix0to1[9][16] = -0.252458020410588;
   fWeightMatrix0to1[10][16] = -1.17423358802133;
   fWeightMatrix0to1[11][16] = 0.289557911021842;
   fWeightMatrix0to1[12][16] = -0.396271573361542;
   fWeightMatrix0to1[13][16] = 0.256407100121214;
   fWeightMatrix0to1[14][16] = -0.21480727912403;
   fWeightMatrix0to1[15][16] = -0.290417923211964;
   fWeightMatrix0to1[16][16] = 0.00375424850729336;
   fWeightMatrix0to1[17][16] = -0.0697003907631098;
   fWeightMatrix0to1[18][16] = 0.295361595686774;
   fWeightMatrix0to1[19][16] = 0.404025239291093;
   fWeightMatrix0to1[20][16] = 0.737265446862241;
   fWeightMatrix0to1[21][16] = 0.781207528936718;
   fWeightMatrix0to1[22][16] = 0.00891131083652004;
   fWeightMatrix0to1[23][16] = -0.560981828729915;
   fWeightMatrix0to1[24][16] = -0.103100223058889;
   fWeightMatrix0to1[25][16] = 0.972740211067869;
   fWeightMatrix0to1[26][16] = 1.70069308798586;
   fWeightMatrix0to1[27][16] = -0.418225853964004;
   fWeightMatrix0to1[28][16] = -0.0884003254542108;
   fWeightMatrix0to1[29][16] = 0.452148338097122;
   fWeightMatrix0to1[30][16] = 0.0304166614644232;
   fWeightMatrix0to1[31][16] = 0.86686184134598;
   fWeightMatrix0to1[32][16] = 1.00818884223878;
   fWeightMatrix0to1[33][16] = -0.20779912806075;
   fWeightMatrix0to1[34][16] = 0.438926299817546;
   fWeightMatrix0to1[35][16] = -2.19847253273307;
   fWeightMatrix0to1[36][16] = 1.40332629268532;
   fWeightMatrix0to1[37][16] = 0.574953259710306;
   fWeightMatrix0to1[38][16] = -0.397621862146044;
   fWeightMatrix0to1[39][16] = -0.00648740054055545;
   fWeightMatrix0to1[0][17] = 0.0810708229412346;
   fWeightMatrix0to1[1][17] = 0.016039401260493;
   fWeightMatrix0to1[2][17] = 0.00271248690541096;
   fWeightMatrix0to1[3][17] = -0.110203707533374;
   fWeightMatrix0to1[4][17] = -0.0434582814236629;
   fWeightMatrix0to1[5][17] = 0.0352954618900383;
   fWeightMatrix0to1[6][17] = 0.148243533059012;
   fWeightMatrix0to1[7][17] = 0.00976028339718059;
   fWeightMatrix0to1[8][17] = 0.111568445512553;
   fWeightMatrix0to1[9][17] = -0.0219147447101027;
   fWeightMatrix0to1[10][17] = 0.0304058918995773;
   fWeightMatrix0to1[11][17] = -0.0113402020966789;
   fWeightMatrix0to1[12][17] = 0.0588840010305435;
   fWeightMatrix0to1[13][17] = -0.0272369504838449;
   fWeightMatrix0to1[14][17] = 0.130327083135782;
   fWeightMatrix0to1[15][17] = -0.106707398993983;
   fWeightMatrix0to1[16][17] = 0.00196375105801742;
   fWeightMatrix0to1[17][17] = -0.180625645036807;
   fWeightMatrix0to1[18][17] = 0.00777724071525984;
   fWeightMatrix0to1[19][17] = -0.0799952166495482;
   fWeightMatrix0to1[20][17] = 0.00363722330840578;
   fWeightMatrix0to1[21][17] = 0.0295278740845352;
   fWeightMatrix0to1[22][17] = 0.0181982841276923;
   fWeightMatrix0to1[23][17] = 0.0597734196154813;
   fWeightMatrix0to1[24][17] = -0.0515326059031849;
   fWeightMatrix0to1[25][17] = -0.147912078562728;
   fWeightMatrix0to1[26][17] = -0.126094034146538;
   fWeightMatrix0to1[27][17] = 0.122035161077383;
   fWeightMatrix0to1[28][17] = -0.215801740998995;
   fWeightMatrix0to1[29][17] = -0.158103962509309;
   fWeightMatrix0to1[30][17] = -0.16561047842997;
   fWeightMatrix0to1[31][17] = 0.116642896202868;
   fWeightMatrix0to1[32][17] = 0.248942871843326;
   fWeightMatrix0to1[33][17] = -0.159456087569543;
   fWeightMatrix0to1[34][17] = -0.157075713358407;
   fWeightMatrix0to1[35][17] = 0.391111631708496;
   fWeightMatrix0to1[36][17] = -0.0206360301320202;
   fWeightMatrix0to1[37][17] = -0.0262776670672845;
   fWeightMatrix0to1[38][17] = 0.271735555513039;
   fWeightMatrix0to1[39][17] = -0.00791328758260013;
   fWeightMatrix0to1[0][18] = 0.0131244200776947;
   fWeightMatrix0to1[1][18] = 0.0657726318400729;
   fWeightMatrix0to1[2][18] = 0.00064191790136764;
   fWeightMatrix0to1[3][18] = -0.000697454437235242;
   fWeightMatrix0to1[4][18] = -0.0471229770661588;
   fWeightMatrix0to1[5][18] = -0.280127634284283;
   fWeightMatrix0to1[6][18] = 0.359517659709049;
   fWeightMatrix0to1[7][18] = -0.0952506856258047;
   fWeightMatrix0to1[8][18] = 0.0732899839494177;
   fWeightMatrix0to1[9][18] = -0.0539460048666825;
   fWeightMatrix0to1[10][18] = -0.0137649974315979;
   fWeightMatrix0to1[11][18] = -0.0611316678368105;
   fWeightMatrix0to1[12][18] = 0.132309015212744;
   fWeightMatrix0to1[13][18] = 0.0805753009138235;
   fWeightMatrix0to1[14][18] = 0.900725314785213;
   fWeightMatrix0to1[15][18] = -0.0787066719936094;
   fWeightMatrix0to1[16][18] = 0.000381391660458281;
   fWeightMatrix0to1[17][18] = -0.00358307330332918;
   fWeightMatrix0to1[18][18] = 0.0105356831615327;
   fWeightMatrix0to1[19][18] = -0.340536907234075;
   fWeightMatrix0to1[20][18] = 0.0611286755984415;
   fWeightMatrix0to1[21][18] = 0.168085792038806;
   fWeightMatrix0to1[22][18] = 0.0110102493383458;
   fWeightMatrix0to1[23][18] = 0.0883450790094019;
   fWeightMatrix0to1[24][18] = -0.289952446800267;
   fWeightMatrix0to1[25][18] = -0.0729104762596051;
   fWeightMatrix0to1[26][18] = 0.025997434883678;
   fWeightMatrix0to1[27][18] = 0.0606902834647784;
   fWeightMatrix0to1[28][18] = -0.259494267724232;
   fWeightMatrix0to1[29][18] = -0.298728545827412;
   fWeightMatrix0to1[30][18] = -0.0319787621760403;
   fWeightMatrix0to1[31][18] = -0.0156548403446562;
   fWeightMatrix0to1[32][18] = -0.112723216579291;
   fWeightMatrix0to1[33][18] = 0.103581032556236;
   fWeightMatrix0to1[34][18] = -0.083408360383226;
   fWeightMatrix0to1[35][18] = -0.0135695979576812;
   fWeightMatrix0to1[36][18] = 0.222944887817851;
   fWeightMatrix0to1[37][18] = -0.0580346720226207;
   fWeightMatrix0to1[38][18] = -0.10466866853647;
   fWeightMatrix0to1[39][18] = -0.00337060031900609;
   fWeightMatrix0to1[0][19] = -0.316708316706024;
   fWeightMatrix0to1[1][19] = 0.490438413446302;
   fWeightMatrix0to1[2][19] = -0.0275430768333746;
   fWeightMatrix0to1[3][19] = -0.315872600760884;
   fWeightMatrix0to1[4][19] = 0.681277507138791;
   fWeightMatrix0to1[5][19] = 0.367270343830228;
   fWeightMatrix0to1[6][19] = -0.678848961724616;
   fWeightMatrix0to1[7][19] = -0.724069052517323;
   fWeightMatrix0to1[8][19] = 0.0649452455068669;
   fWeightMatrix0to1[9][19] = -1.24837535688074;
   fWeightMatrix0to1[10][19] = -0.246742052526148;
   fWeightMatrix0to1[11][19] = 0.222788585998794;
   fWeightMatrix0to1[12][19] = -0.195589307599957;
   fWeightMatrix0to1[13][19] = 0.602035822228515;
   fWeightMatrix0to1[14][19] = 0.677952952251963;
   fWeightMatrix0to1[15][19] = -0.109644821599762;
   fWeightMatrix0to1[16][19] = -0.599482662003343;
   fWeightMatrix0to1[17][19] = -0.521529295400263;
   fWeightMatrix0to1[18][19] = 0.0979736715412147;
   fWeightMatrix0to1[19][19] = -0.559418212638085;
   fWeightMatrix0to1[20][19] = -0.808717763865945;
   fWeightMatrix0to1[21][19] = 0.0266011427300134;
   fWeightMatrix0to1[22][19] = 0.504343565284117;
   fWeightMatrix0to1[23][19] = -1.00705610697696;
   fWeightMatrix0to1[24][19] = -3.69878571031356;
   fWeightMatrix0to1[25][19] = -0.130652583840404;
   fWeightMatrix0to1[26][19] = -0.209226985110284;
   fWeightMatrix0to1[27][19] = -0.00443526181898787;
   fWeightMatrix0to1[28][19] = -1.02234572425561;
   fWeightMatrix0to1[29][19] = -0.29409873712455;
   fWeightMatrix0to1[30][19] = 1.01196254488991;
   fWeightMatrix0to1[31][19] = -0.467677118583828;
   fWeightMatrix0to1[32][19] = 0.792404628816283;
   fWeightMatrix0to1[33][19] = 0.637772491290471;
   fWeightMatrix0to1[34][19] = 0.457394784363735;
   fWeightMatrix0to1[35][19] = 3.94137572826356;
   fWeightMatrix0to1[36][19] = 0.825628755810075;
   fWeightMatrix0to1[37][19] = -0.672075665287554;
   fWeightMatrix0to1[38][19] = 1.11337862420189;
   fWeightMatrix0to1[39][19] = -0.0546049091939267;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 4.2915803146896;
   fWeightMatrix1to2[0][1] = -3.88428219398365;
   fWeightMatrix1to2[0][2] = 0.587018301345725;
   fWeightMatrix1to2[0][3] = -2.85189234063592;
   fWeightMatrix1to2[0][4] = -3.75324519504626;
   fWeightMatrix1to2[0][5] = -3.99097454945082;
   fWeightMatrix1to2[0][6] = 4.0697569732866;
   fWeightMatrix1to2[0][7] = 5.16805467318591;
   fWeightMatrix1to2[0][8] = 4.05992032623723;
   fWeightMatrix1to2[0][9] = 2.93861969216286;
   fWeightMatrix1to2[0][10] = 4.75392543426389;
   fWeightMatrix1to2[0][11] = -3.90928185686894;
   fWeightMatrix1to2[0][12] = -4.90387906570164;
   fWeightMatrix1to2[0][13] = -2.67420629708294;
   fWeightMatrix1to2[0][14] = -5.60083006019887;
   fWeightMatrix1to2[0][15] = 5.15437881983028;
   fWeightMatrix1to2[0][16] = 0.402388700075136;
   fWeightMatrix1to2[0][17] = 4.79976182003212;
   fWeightMatrix1to2[0][18] = 2.64697348306036;
   fWeightMatrix1to2[0][19] = 4.42005714431004;
   fWeightMatrix1to2[0][20] = -3.83624593564429;
   fWeightMatrix1to2[0][21] = 5.90528650120504;
   fWeightMatrix1to2[0][22] = 1.05598738330663;
   fWeightMatrix1to2[0][23] = 4.06487565274371;
   fWeightMatrix1to2[0][24] = 6.90961875846298;
   fWeightMatrix1to2[0][25] = -5.42857624178328;
   fWeightMatrix1to2[0][26] = 5.25761405773147;
   fWeightMatrix1to2[0][27] = -4.00762532849371;
   fWeightMatrix1to2[0][28] = 4.59957670836782;
   fWeightMatrix1to2[0][29] = 3.58361694446647;
   fWeightMatrix1to2[0][30] = -5.35907025729728;
   fWeightMatrix1to2[0][31] = 4.19021091845425;
   fWeightMatrix1to2[0][32] = 4.38570844939137;
   fWeightMatrix1to2[0][33] = 3.50058848219092;
   fWeightMatrix1to2[0][34] = -4.47829358521282;
   fWeightMatrix1to2[0][35] = 7.32223872321061;
   fWeightMatrix1to2[0][36] = 4.86574388971411;
   fWeightMatrix1to2[0][37] = 5.02900807879815;
   fWeightMatrix1to2[0][38] = 4.94280326732778;
   fWeightMatrix1to2[0][39] = -0.527323563357337;
   fWeightMatrix1to2[0][40] = -0.836974324106121;
}

inline double ReadMLPBNN::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPBNN::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPBNN::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLPBNN::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPBNN::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPBNN::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 20.0387992859;
   fMax_1[0][0] = 169.718002319;
   fMin_1[1][0] = 20.1175994873;
   fMax_1[1][0] = 278.061004639;
   fMin_1[2][0] = 20.0387992859;
   fMax_1[2][0] = 278.061004639;
   fMin_1[0][1] = -2.39956998825;
   fMax_1[0][1] = 2.39816999435;
   fMin_1[1][1] = -2.3845000267;
   fMax_1[1][1] = 2.39913010597;
   fMin_1[2][1] = -2.39956998825;
   fMax_1[2][1] = 2.39913010597;
   fMin_1[0][2] = -3.14141988754;
   fMax_1[0][2] = 3.14014005661;
   fMin_1[1][2] = -3.14155006409;
   fMax_1[1][2] = 3.14138007164;
   fMin_1[2][2] = -3.14155006409;
   fMax_1[2][2] = 3.14138007164;
   fMin_1[0][3] = 8.8874502182;
   fMax_1[0][3] = 81.1477966309;
   fMin_1[1][3] = 10.3790998459;
   fMax_1[1][3] = 150.102005005;
   fMin_1[2][3] = 8.8874502182;
   fMax_1[2][3] = 150.102005005;
   fMin_1[0][4] = -2.39977002144;
   fMax_1[0][4] = 2.39869999886;
   fMin_1[1][4] = -2.39748001099;
   fMax_1[1][4] = 2.39791989326;
   fMin_1[2][4] = -2.39977002144;
   fMax_1[2][4] = 2.39869999886;
   fMin_1[0][5] = -3.14139008522;
   fMax_1[0][5] = 3.13953995705;
   fMin_1[1][5] = -3.13930988312;
   fMax_1[1][5] = 3.14006996155;
   fMin_1[2][5] = -3.14139008522;
   fMax_1[2][5] = 3.14006996155;
   fMin_1[0][6] = 5.29546022415;
   fMax_1[0][6] = 58.9183998108;
   fMin_1[1][6] = 5.51318979263;
   fMax_1[1][6] = 90.4963989258;
   fMin_1[2][6] = 5.29546022415;
   fMax_1[2][6] = 90.4963989258;
   fMin_1[0][7] = -2.39901995659;
   fMax_1[0][7] = 2.398250103;
   fMin_1[1][7] = -2.39678001404;
   fMax_1[1][7] = 2.3912498951;
   fMin_1[2][7] = -2.39901995659;
   fMax_1[2][7] = 2.398250103;
   fMin_1[0][8] = -3.14122009277;
   fMax_1[0][8] = 3.14109992981;
   fMin_1[1][8] = -3.14071989059;
   fMax_1[1][8] = 3.13785004616;
   fMin_1[2][8] = -3.14122009277;
   fMax_1[2][8] = 3.14109992981;
   fMin_1[0][9] = 5.00129985809;
   fMax_1[0][9] = 40.5410003662;
   fMin_1[1][9] = 5.00728988647;
   fMax_1[1][9] = 69.7885971069;
   fMin_1[2][9] = 5.00129985809;
   fMax_1[2][9] = 69.7885971069;
   fMin_1[0][10] = -2.39884996414;
   fMax_1[0][10] = 2.39657998085;
   fMin_1[1][10] = -2.3996899128;
   fMax_1[1][10] = 2.39824008942;
   fMin_1[2][10] = -2.3996899128;
   fMax_1[2][10] = 2.39824008942;
   fMin_1[0][11] = -3.13938999176;
   fMax_1[0][11] = 3.14139008522;
   fMin_1[1][11] = -3.14139008522;
   fMax_1[1][11] = 3.1409099102;
   fMin_1[2][11] = -3.14139008522;
   fMax_1[2][11] = 3.14139008522;
   fMin_1[0][12] = -0.0301591008902;
   fMax_1[0][12] = 14.0198001862;
   fMin_1[1][12] = -0.0444267988205;
   fMax_1[1][12] = 3.01027011871;
   fMin_1[2][12] = -0.0444267988205;
   fMax_1[2][12] = 14.0198001862;
   fMin_1[0][13] = -0.0497163012624;
   fMax_1[0][13] = 1.85469996929;
   fMin_1[1][13] = -0.0540362000465;
   fMax_1[1][13] = 0.709349989891;
   fMin_1[2][13] = -0.0540362000465;
   fMax_1[2][13] = 1.85469996929;
   fMin_1[0][14] = 0.299522995949;
   fMax_1[0][14] = 96.7269973755;
   fMin_1[1][14] = 0.275514006615;
   fMax_1[1][14] = 25.4246997833;
   fMin_1[2][14] = 0.275514006615;
   fMax_1[2][14] = 96.7269973755;
   fMin_1[0][15] = 0.15038099885;
   fMax_1[0][15] = 44.9584999084;
   fMin_1[1][15] = 0.135326996446;
   fMax_1[1][15] = 6.75087022781;
   fMin_1[2][15] = 0.135326996446;
   fMax_1[2][15] = 44.9584999084;
   fMin_1[0][16] = 8.75;
   fMax_1[0][16] = 140.74899292;
   fMin_1[1][16] = 14.9264001846;
   fMax_1[1][16] = 120.709999084;
   fMin_1[2][16] = 8.75;
   fMax_1[2][16] = 140.74899292;
   fMin_1[0][17] = 12.0004997253;
   fMax_1[0][17] = 111.925003052;
   fMin_1[1][17] = 12.0264997482;
   fMax_1[1][17] = 96.6280975342;
   fMin_1[2][17] = 12.0004997253;
   fMax_1[2][17] = 111.925003052;
   fMin_1[0][18] = 110.018997192;
   fMax_1[0][18] = 164.99899292;
   fMin_1[1][18] = 110.066001892;
   fMax_1[1][18] = 164.917007446;
   fMin_1[2][18] = 110.018997192;
   fMax_1[2][18] = 164.99899292;
}

//_______________________________________________________________________
inline void ReadMLPBNN::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 19;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesGet.push_back( 11);
   indicesGet.push_back( 12);
   indicesGet.push_back( 13);
   indicesGet.push_back( 14);
   indicesGet.push_back( 15);
   indicesGet.push_back( 16);
   indicesGet.push_back( 17);
   indicesGet.push_back( 18);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);
   indicesPut.push_back( 11);
   indicesPut.push_back( 12);
   indicesPut.push_back( 13);
   indicesPut.push_back( 14);
   indicesPut.push_back( 15);
   indicesPut.push_back( 16);
   indicesPut.push_back( 17);
   indicesPut.push_back( 18);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<19;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPBNN::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPBNN::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
