// Class: ReadMLPBNN
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPBNN
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : JBochenek
Date           : Wed Apr 11 10:35:25 2012
Host           : Linux lnxthry05.hep.fsu.edu 2.6.18-238.5.1.el5 #1 SMP Fri Apr 1 18:41:58 EDT 2011 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/room2/jbochenek/HiggsCombination/TMVAfiles/TMVA-v4.1.2/test
Training events: 10000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "1200" [Number of training cycles]
HiddenLayers: "N+10" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "True" [Use regulator to avoid over-training]
CalculateErrors: "True" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 7
worst_iso_X                   worst_iso_X                   worst_iso_X                   worst_iso_X                                                     'F'    [-0.0444267988205,14.0198001862]
second_worst_iso_X            second_worst_iso_X            second_worst_iso_X            second_worst_iso_X                                              'F'    [-0.0540362000465,1.85469996929]
worst_vertex                  worst_vertex                  worst_vertex                  worst_vertex                                                    'F'    [0.275514006615,96.7269973755]
second_worst_vertex           second_worst_vertex           second_worst_vertex           second_worst_vertex                                             'F'    [0.135326996446,44.9584999084]
mZ                            mZ                            mZ                            mZ                                                              'F'    [8.75,140.74899292]
mZstar                        mZstar                        mZstar                        mZstar                                                          'F'    [12.0004997253,111.925003052]
mbestH                        mbestH                        mbestH                        mbestH                                                          'F'    [110.018997192,164.99899292]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPBNN : public IClassifierReader {

 public:

   // constructor
   ReadMLPBNN( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPBNN" ),
        fNvars( 7 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "worst_iso_X", "second_worst_iso_X", "worst_vertex", "second_worst_vertex", "mZ", "mZstar", "mbestH" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPBNN() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][7];
   double fMax_1[3][7];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[7];
   double fVmax[7];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[7];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[18][8];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][18];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPBNN::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 8; fWeights[0] = new double[8]; 
   fLayerSize[1] = 18; fWeights[1] = new double[18]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.012700129129321;
   fWeightMatrix0to1[1][0] = 1.30088527000916;
   fWeightMatrix0to1[2][0] = -1.14427313601585;
   fWeightMatrix0to1[3][0] = 0.127494322402266;
   fWeightMatrix0to1[4][0] = -0.0599607388719907;
   fWeightMatrix0to1[5][0] = -0.313761043405257;
   fWeightMatrix0to1[6][0] = -0.070469228418519;
   fWeightMatrix0to1[7][0] = 0.00112120490678762;
   fWeightMatrix0to1[8][0] = 0.605858262620105;
   fWeightMatrix0to1[9][0] = 0.0173616088038569;
   fWeightMatrix0to1[10][0] = -0.655438642971656;
   fWeightMatrix0to1[11][0] = 0.078060234853514;
   fWeightMatrix0to1[12][0] = -1.57498717528823;
   fWeightMatrix0to1[13][0] = -0.66585169181965;
   fWeightMatrix0to1[14][0] = 0.761088677488952;
   fWeightMatrix0to1[15][0] = 1.13093088730083;
   fWeightMatrix0to1[16][0] = -0.5894132910434;
   fWeightMatrix0to1[0][1] = -0.00819744763922176;
   fWeightMatrix0to1[1][1] = 2.01874818013341;
   fWeightMatrix0to1[2][1] = -0.662633752832332;
   fWeightMatrix0to1[3][1] = 0.00761588850396328;
   fWeightMatrix0to1[4][1] = 0.00527155584010835;
   fWeightMatrix0to1[5][1] = -0.929446184050283;
   fWeightMatrix0to1[6][1] = -0.030267830370367;
   fWeightMatrix0to1[7][1] = -0.164796070006886;
   fWeightMatrix0to1[8][1] = -0.356490950803436;
   fWeightMatrix0to1[9][1] = 0.00312409879604131;
   fWeightMatrix0to1[10][1] = -0.18971155593655;
   fWeightMatrix0to1[11][1] = 0.170670450203517;
   fWeightMatrix0to1[12][1] = -0.740438461765611;
   fWeightMatrix0to1[13][1] = -0.491907441611392;
   fWeightMatrix0to1[14][1] = 1.98966517032888;
   fWeightMatrix0to1[15][1] = -0.266753887208941;
   fWeightMatrix0to1[16][1] = -0.953477341788016;
   fWeightMatrix0to1[0][2] = 0.140823369157138;
   fWeightMatrix0to1[1][2] = 0.0121262786969652;
   fWeightMatrix0to1[2][2] = 0.433352282407771;
   fWeightMatrix0to1[3][2] = 1.14105847876834;
   fWeightMatrix0to1[4][2] = -0.511036957516627;
   fWeightMatrix0to1[5][2] = 0.656832881879008;
   fWeightMatrix0to1[6][2] = 0.236610990192344;
   fWeightMatrix0to1[7][2] = 0.476551552094245;
   fWeightMatrix0to1[8][2] = 6.80831582464021;
   fWeightMatrix0to1[9][2] = 0.891235906199639;
   fWeightMatrix0to1[10][2] = 0.873560715787099;
   fWeightMatrix0to1[11][2] = -0.81109978739339;
   fWeightMatrix0to1[12][2] = -6.72539641224676;
   fWeightMatrix0to1[13][2] = 5.13766021566976;
   fWeightMatrix0to1[14][2] = 3.9950383070971;
   fWeightMatrix0to1[15][2] = -0.787549922667022;
   fWeightMatrix0to1[16][2] = 1.16264710348909;
   fWeightMatrix0to1[0][3] = 0.0933772305727294;
   fWeightMatrix0to1[1][3] = -0.120099834881178;
   fWeightMatrix0to1[2][3] = 0.562947696815726;
   fWeightMatrix0to1[3][3] = -0.00309974727788752;
   fWeightMatrix0to1[4][3] = -0.0982384525926809;
   fWeightMatrix0to1[5][3] = -0.107495873951781;
   fWeightMatrix0to1[6][3] = -0.264080258230108;
   fWeightMatrix0to1[7][3] = -0.0495001577420598;
   fWeightMatrix0to1[8][3] = -0.35291156066961;
   fWeightMatrix0to1[9][3] = -0.00372796439353111;
   fWeightMatrix0to1[10][3] = -0.361443772141867;
   fWeightMatrix0to1[11][3] = 0.240115566126938;
   fWeightMatrix0to1[12][3] = -4.17392126866929;
   fWeightMatrix0to1[13][3] = 2.28901756406369;
   fWeightMatrix0to1[14][3] = 3.34579040038487;
   fWeightMatrix0to1[15][3] = 1.52521380546864;
   fWeightMatrix0to1[16][3] = -0.0554238774300418;
   fWeightMatrix0to1[0][4] = 0.11524451581023;
   fWeightMatrix0to1[1][4] = 0.689757893825168;
   fWeightMatrix0to1[2][4] = -2.72958024034371;
   fWeightMatrix0to1[3][4] = -0.0137855859668208;
   fWeightMatrix0to1[4][4] = -0.0179159262357279;
   fWeightMatrix0to1[5][4] = -0.735302279252915;
   fWeightMatrix0to1[6][4] = -0.167393558887296;
   fWeightMatrix0to1[7][4] = 0.372604233645802;
   fWeightMatrix0to1[8][4] = 0.183506310447751;
   fWeightMatrix0to1[9][4] = -0.00375018543380594;
   fWeightMatrix0to1[10][4] = 0.880218732410047;
   fWeightMatrix0to1[11][4] = -0.389872445190219;
   fWeightMatrix0to1[12][4] = 0.486921005512624;
   fWeightMatrix0to1[13][4] = 1.08821008312954;
   fWeightMatrix0to1[14][4] = 1.16877391651868;
   fWeightMatrix0to1[15][4] = -2.16879455760323;
   fWeightMatrix0to1[16][4] = 1.92793769095884;
   fWeightMatrix0to1[0][5] = -0.0283586059379652;
   fWeightMatrix0to1[1][5] = 1.09601584436783;
   fWeightMatrix0to1[2][5] = -0.934312746926477;
   fWeightMatrix0to1[3][5] = 0.0321245449458413;
   fWeightMatrix0to1[4][5] = -0.00403349188205148;
   fWeightMatrix0to1[5][5] = 0.123663081656257;
   fWeightMatrix0to1[6][5] = 0.0543817885185051;
   fWeightMatrix0to1[7][5] = -0.300353493951566;
   fWeightMatrix0to1[8][5] = 0.32109959074952;
   fWeightMatrix0to1[9][5] = 0.00479343092301248;
   fWeightMatrix0to1[10][5] = 1.86004765970067;
   fWeightMatrix0to1[11][5] = 0.375985833883235;
   fWeightMatrix0to1[12][5] = -0.475213830395482;
   fWeightMatrix0to1[13][5] = -1.56999560733492;
   fWeightMatrix0to1[14][5] = -0.887731620336801;
   fWeightMatrix0to1[15][5] = 0.610279722369816;
   fWeightMatrix0to1[16][5] = -0.128375380099572;
   fWeightMatrix0to1[0][6] = -0.0294418549387016;
   fWeightMatrix0to1[1][6] = 1.86320356179302;
   fWeightMatrix0to1[2][6] = 1.14098377262234;
   fWeightMatrix0to1[3][6] = 0.00849520175491119;
   fWeightMatrix0to1[4][6] = 0.0014229020873144;
   fWeightMatrix0to1[5][6] = 0.482515136981745;
   fWeightMatrix0to1[6][6] = 0.0484144962336811;
   fWeightMatrix0to1[7][6] = -0.346266908158726;
   fWeightMatrix0to1[8][6] = 0.655608637606854;
   fWeightMatrix0to1[9][6] = 0.00113168630469116;
   fWeightMatrix0to1[10][6] = 0.417610873645522;
   fWeightMatrix0to1[11][6] = 0.473979601100743;
   fWeightMatrix0to1[12][6] = -0.159194881476997;
   fWeightMatrix0to1[13][6] = 0.103278677609468;
   fWeightMatrix0to1[14][6] = -0.319886925056847;
   fWeightMatrix0to1[15][6] = 0.188893932990532;
   fWeightMatrix0to1[16][6] = 0.428004192894027;
   fWeightMatrix0to1[0][7] = -1.4946810551102;
   fWeightMatrix0to1[1][7] = 0.727516005317309;
   fWeightMatrix0to1[2][7] = -0.738496636885558;
   fWeightMatrix0to1[3][7] = -1.84848735136771;
   fWeightMatrix0to1[4][7] = 1.29150550879095;
   fWeightMatrix0to1[5][7] = 0.468458050373292;
   fWeightMatrix0to1[6][7] = 1.20262750286788;
   fWeightMatrix0to1[7][7] = -0.378977950798284;
   fWeightMatrix0to1[8][7] = 6.39960853072007;
   fWeightMatrix0to1[9][7] = -2.76823091574375;
   fWeightMatrix0to1[10][7] = -1.22246112642685;
   fWeightMatrix0to1[11][7] = 0.481102073226784;
   fWeightMatrix0to1[12][7] = -13.6745499064121;
   fWeightMatrix0to1[13][7] = 4.89930931744444;
   fWeightMatrix0to1[14][7] = 8.19634845189001;
   fWeightMatrix0to1[15][7] = 2.1909725216972;
   fWeightMatrix0to1[16][7] = 0.506531507684302;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 2.57625206938551;
   fWeightMatrix1to2[0][1] = -6.4023823573413;
   fWeightMatrix1to2[0][2] = 3.88598412781617;
   fWeightMatrix1to2[0][3] = 1.42488302626651;
   fWeightMatrix1to2[0][4] = -0.703093247982495;
   fWeightMatrix1to2[0][5] = -2.84557821458741;
   fWeightMatrix1to2[0][6] = -2.01182015259935;
   fWeightMatrix1to2[0][7] = 1.58778531280495;
   fWeightMatrix1to2[0][8] = -5.25073149166458;
   fWeightMatrix1to2[0][9] = 1.74896691408878;
   fWeightMatrix1to2[0][10] = 5.23679181069322;
   fWeightMatrix1to2[0][11] = -1.76405172599398;
   fWeightMatrix1to2[0][12] = -9.61607389824172;
   fWeightMatrix1to2[0][13] = -4.63358468164386;
   fWeightMatrix1to2[0][14] = -5.3192977138351;
   fWeightMatrix1to2[0][15] = -7.9476901624973;
   fWeightMatrix1to2[0][16] = 2.92269045043939;
   fWeightMatrix1to2[0][17] = -2.07442916151588;
}

inline double ReadMLPBNN::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPBNN::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPBNN::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLPBNN::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPBNN::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPBNN::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = -0.0301591008902;
   fMax_1[0][0] = 14.0198001862;
   fMin_1[1][0] = -0.0444267988205;
   fMax_1[1][0] = 3.01027011871;
   fMin_1[2][0] = -0.0444267988205;
   fMax_1[2][0] = 14.0198001862;
   fMin_1[0][1] = -0.0497163012624;
   fMax_1[0][1] = 1.85469996929;
   fMin_1[1][1] = -0.0540362000465;
   fMax_1[1][1] = 0.709349989891;
   fMin_1[2][1] = -0.0540362000465;
   fMax_1[2][1] = 1.85469996929;
   fMin_1[0][2] = 0.299522995949;
   fMax_1[0][2] = 96.7269973755;
   fMin_1[1][2] = 0.275514006615;
   fMax_1[1][2] = 25.4246997833;
   fMin_1[2][2] = 0.275514006615;
   fMax_1[2][2] = 96.7269973755;
   fMin_1[0][3] = 0.15038099885;
   fMax_1[0][3] = 44.9584999084;
   fMin_1[1][3] = 0.135326996446;
   fMax_1[1][3] = 6.75087022781;
   fMin_1[2][3] = 0.135326996446;
   fMax_1[2][3] = 44.9584999084;
   fMin_1[0][4] = 8.75;
   fMax_1[0][4] = 140.74899292;
   fMin_1[1][4] = 14.9264001846;
   fMax_1[1][4] = 120.709999084;
   fMin_1[2][4] = 8.75;
   fMax_1[2][4] = 140.74899292;
   fMin_1[0][5] = 12.0004997253;
   fMax_1[0][5] = 111.925003052;
   fMin_1[1][5] = 12.0264997482;
   fMax_1[1][5] = 96.6280975342;
   fMin_1[2][5] = 12.0004997253;
   fMax_1[2][5] = 111.925003052;
   fMin_1[0][6] = 110.018997192;
   fMax_1[0][6] = 164.99899292;
   fMin_1[1][6] = 110.066001892;
   fMax_1[1][6] = 164.917007446;
   fMin_1[2][6] = 110.018997192;
   fMax_1[2][6] = 164.99899292;
}

//_______________________________________________________________________
inline void ReadMLPBNN::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 7;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<7;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPBNN::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPBNN::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
